package com.cst.xinhe.persistence.dao.terminal_road;

import com.cst.xinhe.persistence.model.terminal_road.TerminalRoad;
import com.cst.xinhe.persistence.model.terminal_road.TerminalRoadExample;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;
import java.util.Map;

public interface TerminalRoadMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_road
     *
     * @mbg.generated
     */
    long countByExample(TerminalRoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_road
     *
     * @mbg.generated
     */
    int deleteByExample(TerminalRoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_road
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer terminalRoadId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_road
     *
     * @mbg.generated
     */
    int insert(TerminalRoad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_road
     *
     * @mbg.generated
     */
    int insertSelective(TerminalRoad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_road
     *
     * @mbg.generated
     */
    List<TerminalRoad> selectByExample(TerminalRoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_road
     *
     * @mbg.generated
     */
    TerminalRoad selectByPrimaryKey(Integer terminalRoadId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_road
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TerminalRoad record, @Param("example") TerminalRoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_road
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TerminalRoad record, @Param("example") TerminalRoadExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_road
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TerminalRoad record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_road
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TerminalRoad record);

    List<String> findTimeList(int staffId);

    List<Map<String,Object>> findTerminalRoadByTime(@Param("staffId") int staffId, @Param("currentTime") String currentTime);

    List<Map<String,Object>> findTerminalRoadByInOreTime(@Param("staffId") int staffId, @Param("inOreTime") Date inOreTime, @Param("startTime") Date startTime, @Param("endTime") Date endTime);

    TerminalRoad findNowSiteByStaffId(int staffId);
}
