package com.cst.xinhe.persistence.dao.attendance;

import com.cst.xinhe.persistence.model.attendance.Attendance;
import com.cst.xinhe.persistence.model.attendance.AttendanceExample;

import java.util.Date;
import java.util.List;

import com.cst.xinhe.persistence.model.elasticsearch.EsAttendanceEntity;
import com.cst.xinhe.persistence.vo.req.AttendanceParamsVO;
import com.cst.xinhe.persistence.vo.resp.AttendanceInfoVO;
import org.apache.ibatis.annotations.Param;

public interface AttendanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated
     */
    long countByExample(AttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated
     */
    int deleteByExample(AttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String attendanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated
     */
    int insert(Attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated
     */
    int insertSelective(Attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated
     */
    List<Attendance> selectByExample(AttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated
     */
    Attendance selectByPrimaryKey(String attendanceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Attendance record, @Param("example") AttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Attendance record, @Param("example") AttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Attendance record);


    Attendance findAttendanceByStaffIdAndEndTimeIsNull(Integer staffId);

    List<EsAttendanceEntity> selectAttendanceInfoByParams(AttendanceParamsVO attendanceParamsVO);

    List<EsAttendanceEntity> searchAttendanceByStaffType(@Param("staffType") Integer staffType,@Param("staffName") String staffName, @Param("startTime")Date startTime,@Param("endTime") Date endTime);

    Integer selectAttendanceByStaffId(@Param("staffId")Integer staffId, @Param("startTime")String firstDay1,@Param("endTime") String lastDay1);
}
