package com.cst.xinhe.persistence.dao.attendance;

import com.cst.xinhe.persistence.model.attendance.StaffAttendanceRealRule;
import com.cst.xinhe.persistence.model.attendance.StaffAttendanceRealRuleExample;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.HashMap;
import java.util.List;

public interface StaffAttendanceRealRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_attendance_real_rule
     *
     * @mbg.generated
     */
    long countByExample(StaffAttendanceRealRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_attendance_real_rule
     *
     * @mbg.generated
     */
    int deleteByExample(StaffAttendanceRealRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_attendance_real_rule
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer staffId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_attendance_real_rule
     *
     * @mbg.generated
     */
    int insert(StaffAttendanceRealRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_attendance_real_rule
     *
     * @mbg.generated
     */
    int insertSelective(StaffAttendanceRealRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_attendance_real_rule
     *
     * @mbg.generated
     */
    List<StaffAttendanceRealRule> selectByExample(StaffAttendanceRealRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_attendance_real_rule
     *
     * @mbg.generated
     */
    StaffAttendanceRealRule selectByPrimaryKey(Integer staffId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_attendance_real_rule
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StaffAttendanceRealRule record, @Param("example") StaffAttendanceRealRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_attendance_real_rule
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StaffAttendanceRealRule record, @Param("example") StaffAttendanceRealRuleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_attendance_real_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StaffAttendanceRealRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_attendance_real_rule
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StaffAttendanceRealRule record);

    List<HashMap<String,Object>> getAttendanceStaff(@Param("deptIds") List<Integer> deptIds, @Param("staffName") String staffName);

    List<HashMap<String,Object>> getUnAttendanceStaff(@Param("nowDate") Date nowDate, @Param("deptIds") List<Integer> deptIds, @Param("staffName") String staffName);

    List<HashMap<String,Object>> getOverTimeStaff(@Param("deptIds") List<Integer> deptIds, @Param("staffName") String staffName);

    List<HashMap<String,Object>> getSeriousTimeStaff(@Param("deptIds") List<Integer> deptIds, @Param("staffName") String staffName);

    Integer getUnAttendanceDept(@Param("nowDate") Date nowDate, @Param("deptIds") List<Integer> deptIds);

    Integer getAttendanceDept(@Param("deptIds") List<Integer> deptIds);

    Integer getOverTimeDept(@Param("deptIds") List<Integer> deptIds);

    Integer getSeriousTimeDept(@Param("deptIds") List<Integer> deptIds);

    Long getAttendanceStaffCount(@Param("deptIds") List<Integer> deptIds, @Param("staffName") String staffName);
}
