package com.cst.xinhe.persistence.dao.attendance;


import com.cst.xinhe.persistence.model.attendance.TimeStandard;
import com.cst.xinhe.persistence.model.attendance.TimeStandardExample;
import com.cst.xinhe.persistence.vo.req.TimeStandardVO;
import org.apache.ibatis.annotations.Param;

import java.sql.Time;
import java.util.List;

public interface TimeStandardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    long countByExample(TimeStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    int deleteByExample(TimeStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer timeStandardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    int insert(TimeStandard record);
    int insertVo(TimeStandardVO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    int insertSelective(TimeStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    List<TimeStandard> selectByExample(TimeStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    TimeStandard selectByPrimaryKey(Integer timeStandardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TimeStandard record, @Param("example") TimeStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TimeStandard record, @Param("example") TimeStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TimeStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TimeStandard record);

    List<TimeStandardVO> selectTimeStandardInfo(@Param("timeStandardName") String timeStandardName, @Param("startTime") Time startTime);

    TimeStandardVO selectTimeStandardInfoByStaffId(@Param(value = "staffId") Integer staffId);
}
