package com.cst.xinhe.persistence.dao.rt_gas;

import com.cst.xinhe.persistence.model.rt_gas.GasPositionWarn;
import com.cst.xinhe.persistence.model.rt_gas.GasPositionWarnExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GasPositionWarnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_position_warn
     *
     * @mbg.generated
     */
    long countByExample(GasPositionWarnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_position_warn
     *
     * @mbg.generated
     */
    int deleteByExample(GasPositionWarnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_position_warn
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long gasPositionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_position_warn
     *
     * @mbg.generated
     */
    int insert(GasPositionWarn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_position_warn
     *
     * @mbg.generated
     */
    int insertSelective(GasPositionWarn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_position_warn
     *
     * @mbg.generated
     */
    List<GasPositionWarn> selectByExample(GasPositionWarnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_position_warn
     *
     * @mbg.generated
     */
    GasPositionWarn selectByPrimaryKey(Long gasPositionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_position_warn
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GasPositionWarn record, @Param("example") GasPositionWarnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_position_warn
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GasPositionWarn record, @Param("example") GasPositionWarnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_position_warn
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GasPositionWarn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_position_warn
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GasPositionWarn record);
}
