package com.cst.xinhe.persistence.dao.rt_gas;


import com.cst.xinhe.persistence.model.rt_gas.GasPosition;
import com.cst.xinhe.persistence.model.rt_gas.GasPositionExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GasPositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_position
     *
     * @mbg.generated
     */
    long countByExample(GasPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_position
     *
     * @mbg.generated
     */
    int deleteByExample(GasPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_position
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long gasPositionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_position
     *
     * @mbg.generated
     */
    int insert(GasPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_position
     *
     * @mbg.generated
     */
    int insertSelective(GasPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_position
     *
     * @mbg.generated
     */
    List<GasPosition> selectByExample(GasPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_position
     *
     * @mbg.generated
     */
    GasPosition selectByPrimaryKey(Long gasPositionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_position
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GasPosition record, @Param("example") GasPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_position
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GasPosition record, @Param("example") GasPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_position
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GasPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_position
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GasPosition record);

    void insertGasPositions(@Param("gasPositions") List<GasPosition> gasPositions);
}
