package com.cst.xinhe.persistence.dao.rt_gas;

import com.cst.xinhe.persistence.model.rt_gas.RtGasInfoWarn;
import com.cst.xinhe.persistence.model.rt_gas.RtGasInfoWarnExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RtGasInfoWarnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info_warn
     *
     * @mbg.generated
     */
    long countByExample(RtGasInfoWarnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info_warn
     *
     * @mbg.generated
     */
    int deleteByExample(RtGasInfoWarnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info_warn
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer rtWarnGasInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info_warn
     *
     * @mbg.generated
     */
    int insert(RtGasInfoWarn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info_warn
     *
     * @mbg.generated
     */
    int insertSelective(RtGasInfoWarn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info_warn
     *
     * @mbg.generated
     */
    List<RtGasInfoWarn> selectByExample(RtGasInfoWarnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info_warn
     *
     * @mbg.generated
     */
    RtGasInfoWarn selectByPrimaryKey(Integer rtWarnGasInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info_warn
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RtGasInfoWarn record, @Param("example") RtGasInfoWarnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info_warn
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RtGasInfoWarn record, @Param("example") RtGasInfoWarnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info_warn
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RtGasInfoWarn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info_warn
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RtGasInfoWarn record);
}
