package com.cst.xinhe.persistence.dao.rt_gas;

import com.cst.xinhe.persistence.model.rt_gas.RtGasInfo;
import com.cst.xinhe.persistence.model.rt_gas.RtGasInfoExample;
import com.cst.xinhe.persistence.vo.resp.GasWSRespVO;
import org.apache.ibatis.annotations.Param;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public interface RtGasInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    long countByExample(RtGasInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    int deleteByExample(RtGasInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer rtGasInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    int insert(RtGasInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    int insertSelective(RtGasInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    List<RtGasInfo> selectByExample(RtGasInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    RtGasInfo selectByPrimaryKey(Integer rtGasInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RtGasInfo record, @Param("example") RtGasInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RtGasInfo record, @Param("example") RtGasInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RtGasInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rt_gas_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RtGasInfo record);

    List<GasWSRespVO> selectGasInfoByStaffName(@Param("staffName") String staffName);

    Map<String, Object> selectGasInfoByTerminalLastTime(Integer terminalId);

    List<Map<String, Object>> selectGasInfoLastTenRecords(int number);

    HashMap<String,Object> selectAllGasFaultNum();

    HashMap<String,Object> findRecentlyGasInfoByStaffId(Integer staffId);

    List<GasWSRespVO> selectGasRoadByStaffId(Integer staffId);

    List<GasWSRespVO> selectGasInfoByRecently();


    List<Map<String,Object>> selectGasInfoLastTenData(int number);
}
