package com.cst.xinhe.persistence.dao.warn_level;

import com.cst.xinhe.persistence.model.warn_level.GasStandard;
import com.cst.xinhe.persistence.model.warn_level.GasStandardExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GasStandardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_standard
     *
     * @mbg.generated
     */
    long countByExample(GasStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_standard
     *
     * @mbg.generated
     */
    int deleteByExample(GasStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_standard
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer standardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_standard
     *
     * @mbg.generated
     */
    int insert(GasStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_standard
     *
     * @mbg.generated
     */
    int insertSelective(GasStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_standard
     *
     * @mbg.generated
     */
    List<GasStandard> selectByExample(GasStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_standard
     *
     * @mbg.generated
     */
    GasStandard selectByPrimaryKey(Integer standardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_standard
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GasStandard record, @Param("example") GasStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_standard
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GasStandard record, @Param("example") GasStandardExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_standard
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GasStandard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gas_standard
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GasStandard record);
}
