package com.cst.xinhe.persistence.dao.warn_level;

import com.cst.xinhe.persistence.model.warn_level.LevelData;
import com.cst.xinhe.persistence.model.warn_level.LevelDataExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface LevelDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level_data
     *
     * @mbg.generated
     */
    long countByExample(LevelDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level_data
     *
     * @mbg.generated
     */
    int deleteByExample(LevelDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level_data
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level_data
     *
     * @mbg.generated
     */
    int insert(LevelData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level_data
     *
     * @mbg.generated
     */
    int insertSelective(LevelData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level_data
     *
     * @mbg.generated
     */
    List<LevelData> selectByExample(LevelDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level_data
     *
     * @mbg.generated
     */
    LevelData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level_data
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LevelData record, @Param("example") LevelDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level_data
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LevelData record, @Param("example") LevelDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LevelData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table level_data
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LevelData record);

    Map<String ,Object> selectRangUrlByLevelDataId(Integer levelDataId);
}
