<<<<<<< HEAD
server:
  port: 8775
spring:
  application:
    name: attendance-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761
feign:
  hystrix:
    enabled: true
=======
spring:
  application:
    name: attendance-service
>>>>>>> 56316ad2da6b443878666a88c99198a60c8ee18e
