package com.cst.xinhe.persistence.dao.overman_area;


import com.cst.xinhe.persistence.model.overman_area.OvermanArea;
import com.cst.xinhe.persistence.model.overman_area.OvermanAreaExample;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.HashMap;
import java.util.List;

public interface OvermanAreaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overman_area
     *
     * @mbg.generated
     */
    long countByExample(OvermanAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overman_area
     *
     * @mbg.generated
     */
    int deleteByExample(OvermanAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overman_area
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer overmanAreaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overman_area
     *
     * @mbg.generated
     */
    int insert(OvermanArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overman_area
     *
     * @mbg.generated
     */
    int insertSelective(OvermanArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overman_area
     *
     * @mbg.generated
     */
    List<OvermanArea> selectByExample(OvermanAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overman_area
     *
     * @mbg.generated
     */
    OvermanArea selectByPrimaryKey(Integer overmanAreaId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overman_area
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OvermanArea record, @Param("example") OvermanAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overman_area
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OvermanArea record, @Param("example") OvermanAreaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overman_area
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OvermanArea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table overman_area
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OvermanArea record);

    List<OvermanArea> getOvermanAreaInfo(@Param("starOverTime") Date starOverTime,@Param("endOverTime") Date endOverTime,@Param("areaName") String areaName);

    List<HashMap<String, Object>> getOvermanStaffInfo( @Param("staffName") String staffName,@Param("overmanAreaId") Integer overmanAreaId);
}