package com.cst.xinhe.persistence.model.t_partition;


import java.io.Serializable;
import java.util.List;

public class Partition implements Serializable {


    private static final long serialVersionUID = -4576682500234944279L;

    private Integer id;


    private String partitionName;


    private String partitionDesc;


    private Integer parentId;

    private String type;
    private Integer sort;

    //封装数据
    private List<Partition> children;
    private String label;


    public List<Partition> getChildren() {
        return children;
    }

    public void setChildren(List<Partition> children) {
        this.children = children;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    public String getPartitionName() {
        return partitionName;
    }


    public void setPartitionName(String partitionName) {
        this.partitionName = partitionName == null ? null : partitionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partition.partition_desc
     *
     * @return the value of partition.partition_desc
     *
     * @mbg.generated
     */
    public String getPartitionDesc() {
        return partitionDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partition.partition_desc
     *
     * @param partitionDesc the value for partition.partition_desc
     *
     * @mbg.generated
     */
    public void setPartitionDesc(String partitionDesc) {
        this.partitionDesc = partitionDesc == null ? null : partitionDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partition.parent_id
     *
     * @return the value of partition.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partition.parent_id
     *
     * @param parentId the value for partition.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partition.type
     *
     * @return the value of partition.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partition.type
     *
     * @param type the value for partition.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partition.sort
     *
     * @return the value of partition.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partition.sort
     *
     * @param sort the value for partition.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }
}
