server:
  port: 5000
spring:
  application:
    name: monitor-admin
      #security:
      #user:
      #name: 'admin'
    #password: 'admin'
  #mail:
    #host: smtp.qq.com
    #username: 1447273837@qq.com
    #password: jjqgiuumteirhhei
    #properties:
      #mail:
       #smtp:
         #auth: true
         #starttls:
           #enable: true
           #required: true
  # 发送给谁
  boot:
    admin:
      notify:
       mail:
         to: 70150451@qq.com
  # 是谁发送出去的
         from: 1447273837@qq.com

eureka:
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
      # health-check-url-path: /actuator/health
      #metadata-map:
      #user.name: ${spring.security.user.name}
    #user.password: ${spring.security.user.password}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

