package com.cst.xinhe.persistence.model.updateIp;

import java.util.Date;

public class StationIpPort {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_ip_port.station_id
     *
     * @mbg.generated
     */
    private Integer stationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_ip_port.station_ip
     *
     * @mbg.generated
     */
    private String stationIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_ip_port.station_port
     *
     * @mbg.generated
     */
    private Integer stationPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station_ip_port.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_ip_port.station_id
     *
     * @return the value of station_ip_port.station_id
     *
     * @mbg.generated
     */
    public Integer getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_ip_port.station_id
     *
     * @param stationId the value for station_ip_port.station_id
     *
     * @mbg.generated
     */
    public void setStationId(Integer stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_ip_port.station_ip
     *
     * @return the value of station_ip_port.station_ip
     *
     * @mbg.generated
     */
    public String getStationIp() {
        return stationIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_ip_port.station_ip
     *
     * @param stationIp the value for station_ip_port.station_ip
     *
     * @mbg.generated
     */
    public void setStationIp(String stationIp) {
        this.stationIp = stationIp == null ? null : stationIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_ip_port.station_port
     *
     * @return the value of station_ip_port.station_port
     *
     * @mbg.generated
     */
    public Integer getStationPort() {
        return stationPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_ip_port.station_port
     *
     * @param stationPort the value for station_ip_port.station_port
     *
     * @mbg.generated
     */
    public void setStationPort(Integer stationPort) {
        this.stationPort = stationPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station_ip_port.update_time
     *
     * @return the value of station_ip_port.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station_ip_port.update_time
     *
     * @param updateTime the value for station_ip_port.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}