spring:
  application:
    name: kafka-sender-service
  kafka:
    partition-number: 3
    # 指定kafka 代理地址，可以多个
    producer:
      retries: 3 # 重试3次
      # 每次批量发送消息的数量
      batch-size: 16384
      # 缓存容量
      buffer-memory: 33554432
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      bootstrap-servers: 192.168.1.182:9092
    consumer:
      # 指定默认消费者group id
      group-id: test
      max-poll-records: 1000  #最大拉取最大1000
      auto-offset-reset: earliest
      #自动提交
      enable-auto-commit: true
      auto-commit-interval: 1000
      # 指定消息key和消息体的编解码方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-servers: 192.168.1.182:9092

    # 指定listener 容器中的线程数，用于提高并发量
    listener:
      concurrency: 4
server:
  port: 8766
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#feign:
#  hystrix:
#    enabled: true #打开添加熔断器hystrix
