package com.cst.xinhe.persistence.dao.staff;

import com.cst.xinhe.persistence.model.staff.StaffOrganization;
import com.cst.xinhe.persistence.model.staff.StaffOrganizationExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StaffOrganizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_organization
     *
     * @mbg.generated
     */
    long countByExample(StaffOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_organization
     *
     * @mbg.generated
     */
    int deleteByExample(StaffOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_organization
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_organization
     *
     * @mbg.generated
     */
    int insert(StaffOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_organization
     *
     * @mbg.generated
     */
    int insertSelective(StaffOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_organization
     *
     * @mbg.generated
     */
    List<StaffOrganization> selectByExample(StaffOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_organization
     *
     * @mbg.generated
     */
    StaffOrganization selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_organization
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StaffOrganization record, @Param("example") StaffOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_organization
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StaffOrganization record, @Param("example") StaffOrganizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_organization
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StaffOrganization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_organization
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StaffOrganization record);
}
