package com.cst.xinhe.persistence.dao.staff;

public interface StaffGroupMapper {
   /* *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_group
     *
     * @mbg.generated
     *//*
    long countByExample(AStaffGroupExample example);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_group
     *
     * @mbg.generated
     *//*
    int deleteByExample(AStaffGroupExample example);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_group
     *
     * @mbg.generated
     *//*
    int deleteByPrimaryKey(Integer groupId);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_group
     *
     * @mbg.generated
     *//*
    int insert(AStaffGroup record);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_group
     *
     * @mbg.generated
     *//*
    int insertSelective(AStaffGroup record);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_group
     *
     * @mbg.generated
     *//*
    List<AStaffGroup> selectByExample(AStaffGroupExample example);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_group
     *
     * @mbg.generated
     *//*
    AStaffGroup selectByPrimaryKey(Integer groupId);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_group
     *
     * @mbg.generated
     *//*
    int updateByExampleSelective(@Param("record") AStaffGroup record, @Param("example") AStaffGroupExample example);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_group
     *
     * @mbg.generated
     *//*
    int updateByExample(@Param("record") AStaffGroup record, @Param("example") AStaffGroupExample example);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_group
     *
     * @mbg.generated
     *//*
    int updateByPrimaryKeySelective(AStaffGroup record);

    *//**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_group
     *
     * @mbg.generated
     *//*
    int updateByPrimaryKey(AStaffGroup record);

    List<AStaffGroup> selectAllStaffGroups();

    List<AStaffGroup> selectStaffGroupsByDeptId(Integer deptId);

    List<StaffGroupDto> selectStaffGroupsByDeptIdOfStaffDept(Integer deptId);


    Integer countStaffNumByGroupId(Integer groupId);

    StaffGroupDto selectGroupDtoByGroupId(Integer groupId);*/
}
