package com.cst.xinhe.persistence.dao.rang_setting;


import com.cst.xinhe.persistence.model.rang_setting.RangSetting;
import com.cst.xinhe.persistence.model.rang_setting.RangSettingExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RangSettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rang_setting
     *
     * @mbg.generated
     */
    long countByExample(RangSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rang_setting
     *
     * @mbg.generated
     */
    int deleteByExample(RangSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rang_setting
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rang_setting
     *
     * @mbg.generated
     */
    int insert(RangSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rang_setting
     *
     * @mbg.generated
     */
    int insertSelective(RangSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rang_setting
     *
     * @mbg.generated
     */
    List<RangSetting> selectByExample(RangSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rang_setting
     *
     * @mbg.generated
     */
    RangSetting selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rang_setting
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") RangSetting record, @Param("example") RangSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rang_setting
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") RangSetting record, @Param("example") RangSettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rang_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(RangSetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rang_setting
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(RangSetting record);
}
