package com.cst.xinhe.persistence.dao.mac_station;

import com.cst.xinhe.persistence.model.mac_station.MacStation;
import com.cst.xinhe.persistence.model.mac_station.MacStationExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface MacStationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mac_station
     *
     * @mbg.generated
     */
    long countByExample(MacStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mac_station
     *
     * @mbg.generated
     */
    int deleteByExample(MacStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mac_station
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String macStationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mac_station
     *
     * @mbg.generated
     */
    int insert(MacStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mac_station
     *
     * @mbg.generated
     */
    int insertSelective(MacStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mac_station
     *
     * @mbg.generated
     */
    List<MacStation> selectByExample(MacStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mac_station
     *
     * @mbg.generated
     */
    MacStation selectByPrimaryKey(String macStationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mac_station
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MacStation record, @Param("example") MacStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mac_station
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MacStation record, @Param("example") MacStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mac_station
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MacStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mac_station
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MacStation record);

    List<Map<String, Object>> selectCountMacByStationId();

    boolean selectMacExistByMac(String mac);

    void deleteByMac(String mac);

    List<MacStation> selectMacStationByStationId(Integer stationId);
}
