server:
  port: 8771
  ssl:
      key-store: zkxh.keystore
      #密钥库密码
      key-store-password: 123456
      keyStoreType: JKS
      keyAlias: zkxh
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: ws-push-service
eureka:
  instance:
    lease-expiration-duration-in-seconds: 2   #告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    lease-renewal-interval-in-seconds: 1     #每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
  client:
    service-url:
      defaultZone: http://192.168.1.101:8761/eureka/
#打印日志
logging:
  level:
    #org.springframework.web: DEBUG
    com.cst.xinhe.persistence.dao: DEBUG
  config: classpath:logback-boot.xml
