server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    max-connections: 20000
    accept-count: 1000
  port: 8771
  ssl:
      key-store: zkxh.keystore
      #密钥库密码
      key-store-password: 123456
      keyStoreType: JKS
      keyAlias: zkxh
ribbon:
  ReadTimeout: 3500 #请求处理的超时时间
  ConnectTimeout: 1000 #请求连接的超时时间
  OkToRetryOnAllOperations: false # 对所有的操作请求都进行重试，如果是get则可以，如果是post,put等操作没有实现幂等的情况下是很危险的，所以设置为false
  SocketTimeout: 3500
  MaxAutoRetries: 1 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试
  MaxAutoRetriesNextServer: 1  #切换实例的重试次数
  eureka:
    enabled: true
#线程策略
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
          #        isolation:
          #          strategy: SEMAPHORE
          #          semaphore:
          #            maxConcurrentRequests: 500
          thread:
            timeoutInMilliseconds: 20000
feign:
  compression:
    request:
      enabled: true
      mime-types: text/html,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
  hystrix:
    enabled: true
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
spring:
  application:
    name: ws-push-service
eureka:
  instance:
    lease-expiration-duration-in-seconds: 2   #告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    lease-renewal-interval-in-seconds: 1     #每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#打印日志
logging:
  level:
    #org.springframework.web: DEBUG
    com.cst.xinhe.persistence.dao: DEBUG
  config: classpath:logback-boot.xml
