server:
  port: 8771
  ssl:
      key-store: zkxh.keystore
      #密钥库密码
      key-store-password: 123456
      keyStoreType: JKS
      keyAlias: zkxh
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: ws-push-service
eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.47:8761/eureka/
#打印日志
logging:
  level:
    #org.springframework.web: DEBUG
    com.cst.xinhe.persistence.dao: DEBUG
  config: classpath:logback-boot.xml
