package com.cst.xinhe.persistence.dao.chat;

import com.cst.xinhe.persistence.model.chat.TemporarySendList;
import com.cst.xinhe.persistence.model.chat.TemporarySendListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TemporarySendListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temporary_send_list
     *
     * @mbg.generated
     */
    long countByExample(TemporarySendListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temporary_send_list
     *
     * @mbg.generated
     */
    int deleteByExample(TemporarySendListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temporary_send_list
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer temporarySendListId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temporary_send_list
     *
     * @mbg.generated
     */
    int insert(TemporarySendList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temporary_send_list
     *
     * @mbg.generated
     */
    int insertSelective(TemporarySendList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temporary_send_list
     *
     * @mbg.generated
     */
    List<TemporarySendList> selectByExample(TemporarySendListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temporary_send_list
     *
     * @mbg.generated
     */
    TemporarySendList selectByPrimaryKey(Integer temporarySendListId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temporary_send_list
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TemporarySendList record, @Param("example") TemporarySendListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temporary_send_list
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TemporarySendList record, @Param("example") TemporarySendListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temporary_send_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TemporarySendList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temporary_send_list
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TemporarySendList record);

    List<TemporarySendList> checkWaitingForDataToBeSent(@Param("terminalId") Integer terminalId);

    void updateTemporarySendListIsSend(@Param("id") Integer id);
}
