eureka:
  client :
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/,http://127.0.0.1:8762/eureka/
server:
  port: 8443
#  ssl:
#    key-store: zkxh.keystore
#    #密钥库密码
#    key-store-password: 123456
#    keyStoreType: JKS
#    keyAlias: zkxh
spring:
  application:
    name: service-zuul
  datasource:
        druid:
          url: jdbc:mysql://192.168.1.182:3306/zkxh_test1
          username: root
          password: 123456
          db-type: com.alibaba.druid.pool.DruidDataSource
          filter: stat
          max-active: 20
          initial-size: 1
          max-wait: 60000
          min-idle: 1
          time-between-eviction-runs-millis: 6000
          min-evictable-idle-time-millis: 300000
          validation-query: select 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          pool-prepared-statements: true
          max-open-prepared-statements: 20
  #配置redis数据库
  redis:
    database: 15
    host: 192.168.1.182
    port: 6379
    #    password: root
    timeout: 50000
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 5000
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 5000
        # 连接池中的最小空闲连接
        min-idle: 200
zuul:
  routes:
    attendance:
      path: /attendance/**
      serviceId: attendance-service
    staff-group-terminal:
      path: /staff/**
      serviceId: staff-group-terminal-service
    station-partition:
      path: /station/**
      serviceId: station-partition-service
    system-service:
      path: /system/**
      serviceId: system-service
      # 加了url指定到每一个服务，就不需要指定serviceId，不可以负载均衡
      # url: http://localhost:8762
#    base:
#      path: /base/**
#      serviceId: base-service
    chat:
      path: /chat/**
      serviceId: chat-message-service
#    common:
#      path: /common/**
#      serviceId: common
    gas:
      path: /gas/**
      serviceId: gas-service
    user:
        path: /user/**
        serviceId: service-zuul
  prefix: /v1
  sensitive-headers: Access-Control-Allow-Origin
  ignored-headers: Access-Control-Allow-Origin,H-APP-Id,Token,APPToken
#  host:
#    connect-timeout-millis: 10000
#    socket-timeout-millis: 60000
mybatis:
  mapper-locations: com/cst/xinhe/persistence/dao/*.*/*.xml
#  type-aliases-package: com.cst.xinhe.persistence.model
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: count=countSql
redis:
  expireTime: 86400




