netty:
  port: 9999
spring:
  application:
    name: voice-monitor-server
server:
  port: 8767
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true #熔断器hystrix
#打印日志
logging:
  level:
    #org.springframework.web: DEBUG
    com.cst.xinhe.persistence.dao: DEBUG
  config: classpath:logback-boot.xml

