netty:
  port: 9999
spring:
  application:
    name: voice-monitor-server
server:
  port: 8767
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true #熔断器hystrix


