package com.cst.xinhe.persistence.dao.t_partition;


import com.cst.xinhe.persistence.model.t_partition.Partition;
import com.cst.xinhe.persistence.model.t_partition.PartitionExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PartitionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partition
     *
     * @mbg.generated
     */
    long countByExample(PartitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partition
     *
     * @mbg.generated
     */
    int deleteByExample(PartitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partition
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partition
     *
     * @mbg.generated
     */
    int insert(Partition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partition
     *
     * @mbg.generated
     */
    int insertSelective(Partition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partition
     *
     * @mbg.generated
     */
    List<Partition> selectByExample(PartitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partition
     *
     * @mbg.generated
     */
    Partition selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partition
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Partition record, @Param("example") PartitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partition
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Partition record, @Param("example") PartitionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partition
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Partition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_partition
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Partition record);
}
