spring:
  application:
    name: kafka-consumer-service
  datasource:
    druid:
      url: jdbc:mysql://192.168.1.182:3306/zkxh_test1
      username: root
      password: 123456
      db-type: com.alibaba.druid.pool.DruidDataSource
      filter: stat
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 6000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  kafka:
    partition-number: 3
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      bootstrap-servers: 192.168.1.182:9092
    consumer:
      group-id: test
      max-poll-records: 1000
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-servers: 192.168.1.182:9092
    listener:
      concurrency: 4
server:
  port: 8773
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
mybatis:
  mapper-locations: com/cst/xinhe/persistence/dao/**/*.xml
#  type-aliases-package: com.cst.xinhe.persistence.model
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: count=countSql

