package com.cst.xinhe.persistence.dao.coordinate;


import com.cst.xinhe.persistence.dto.warning_area.CoordinateDto;
import com.cst.xinhe.persistence.model.coordinate.Coordinate;
import com.cst.xinhe.persistence.model.coordinate.CoordinateExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CoordinateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinate
     *
     * @mbg.generated
     */
    long countByExample(CoordinateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinate
     *
     * @mbg.generated
     */
    int deleteByExample(CoordinateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinate
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer coordinateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinate
     *
     * @mbg.generated
     */
    int insert(Coordinate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinate
     *
     * @mbg.generated
     */
    int insertSelective(Coordinate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinate
     *
     * @mbg.generated
     */
    List<Coordinate> selectByExample(CoordinateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinate
     *
     * @mbg.generated
     */
    Coordinate selectByPrimaryKey(Integer coordinateId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinate
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Coordinate record, @Param("example") CoordinateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinate
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Coordinate record, @Param("example") CoordinateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinate
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Coordinate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coordinate
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Coordinate record);

    List<CoordinateDto> selectCoordinateInfoByAreaId(Integer areaId);

    boolean selectCountCoordinateByWarningAreaId(int warningAreaId);
}
