package com.cst.xinhe.persistence.model.lack_electric;

import java.io.Serializable;
import java.util.Date;

public class LackElectric implements Serializable,Cloneable {


    private static final long serialVersionUID = -4563013277223732016L;
    private static LackElectric lackElectric = new LackElectric();

    public static LackElectric getInstance(){
        try {
            return (LackElectric) lackElectric.clone();
        } catch (CloneNotSupportedException e) {
            e.printStackTrace();
        }
        return new LackElectric();
    }
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lack_electric.lack_electric_id
     *
     * @mbg.generated
     */
    private Integer lackElectricId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lack_electric.upload_id
     *
     * @mbg.generated
     */
    private Integer uploadId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lack_electric.upload_time
     *
     * @mbg.generated
     */
    private Date uploadTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lack_electric.electric_value
     *
     * @mbg.generated
     */
    private Integer electricValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lack_electric.lack_type
     *
     * @mbg.generated
     */
    private Integer lackType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lack_electric.is_read
     *
     * @mbg.generated
     */
    private Integer isRead;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lack_electric.lack_electric_id
     *
     * @return the value of lack_electric.lack_electric_id
     *
     * @mbg.generated
     */
    public Integer getLackElectricId() {
        return lackElectricId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lack_electric.lack_electric_id
     *
     * @param lackElectricId the value for lack_electric.lack_electric_id
     *
     * @mbg.generated
     */
    public void setLackElectricId(Integer lackElectricId) {
        this.lackElectricId = lackElectricId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lack_electric.upload_id
     *
     * @return the value of lack_electric.upload_id
     *
     * @mbg.generated
     */
    public Integer getUploadId() {
        return uploadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lack_electric.upload_id
     *
     * @param uploadId the value for lack_electric.upload_id
     *
     * @mbg.generated
     */
    public void setUploadId(Integer uploadId) {
        this.uploadId = uploadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lack_electric.upload_time
     *
     * @return the value of lack_electric.upload_time
     *
     * @mbg.generated
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lack_electric.upload_time
     *
     * @param uploadTime the value for lack_electric.upload_time
     *
     * @mbg.generated
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lack_electric.electric_value
     *
     * @return the value of lack_electric.electric_value
     *
     * @mbg.generated
     */
    public Integer getElectricValue() {
        return electricValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lack_electric.electric_value
     *
     * @param electricValue the value for lack_electric.electric_value
     *
     * @mbg.generated
     */
    public void setElectricValue(Integer electricValue) {
        this.electricValue = electricValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lack_electric.lack_type
     *
     * @return the value of lack_electric.lack_type
     *
     * @mbg.generated
     */
    public Integer getLackType() {
        return lackType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lack_electric.lack_type
     *
     * @param lackType the value for lack_electric.lack_type
     *
     * @mbg.generated
     */
    public void setLackType(Integer lackType) {
        this.lackType = lackType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lack_electric.is_read
     *
     * @return the value of lack_electric.is_read
     *
     * @mbg.generated
     */
    public Integer getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lack_electric.is_read
     *
     * @param isRead the value for lack_electric.is_read
     *
     * @mbg.generated
     */
    public void setIsRead(Integer isRead) {
        this.isRead = isRead;
    }
}
