package com.cst.xinhe.persistence.model.warn_level;

public class GasWarnSetting {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gas_warn_setting.gas_warn_setting_id
     *
     * @mbg.generated
     */
    private Integer gasWarnSettingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gas_warn_setting.gas_type
     *
     * @mbg.generated
     */
    private Integer gasType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gas_warn_setting.warn_level_id
     *
     * @mbg.generated
     */
    private Integer warnLevelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gas_warn_setting.multiple
     *
     * @mbg.generated
     */
    private Double multiple;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gas_warn_setting.lower_limit
     *
     * @mbg.generated
     */
    private Double lowerLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gas_warn_setting.upper_limit
     *
     * @mbg.generated
     */
    private Double upperLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gas_warn_setting.lower_continued_time
     *
     * @mbg.generated
     */
    private Integer lowerContinuedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gas_warn_setting.upper_continued_time
     *
     * @mbg.generated
     */
    private Integer upperContinuedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gas_warn_setting.standard_id
     *
     * @mbg.generated
     */
    private Integer standardId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_warn_setting.gas_warn_setting_id
     *
     * @return the value of gas_warn_setting.gas_warn_setting_id
     *
     * @mbg.generated
     */
    public Integer getGasWarnSettingId() {
        return gasWarnSettingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_warn_setting.gas_warn_setting_id
     *
     * @param gasWarnSettingId the value for gas_warn_setting.gas_warn_setting_id
     *
     * @mbg.generated
     */
    public void setGasWarnSettingId(Integer gasWarnSettingId) {
        this.gasWarnSettingId = gasWarnSettingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_warn_setting.gas_type
     *
     * @return the value of gas_warn_setting.gas_type
     *
     * @mbg.generated
     */
    public Integer getGasType() {
        return gasType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_warn_setting.gas_type
     *
     * @param gasType the value for gas_warn_setting.gas_type
     *
     * @mbg.generated
     */
    public void setGasType(Integer gasType) {
        this.gasType = gasType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_warn_setting.warn_level_id
     *
     * @return the value of gas_warn_setting.warn_level_id
     *
     * @mbg.generated
     */
    public Integer getWarnLevelId() {
        return warnLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_warn_setting.warn_level_id
     *
     * @param warnLevelId the value for gas_warn_setting.warn_level_id
     *
     * @mbg.generated
     */
    public void setWarnLevelId(Integer warnLevelId) {
        this.warnLevelId = warnLevelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_warn_setting.multiple
     *
     * @return the value of gas_warn_setting.multiple
     *
     * @mbg.generated
     */
    public Double getMultiple() {
        return multiple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_warn_setting.multiple
     *
     * @param multiple the value for gas_warn_setting.multiple
     *
     * @mbg.generated
     */
    public void setMultiple(Double multiple) {
        this.multiple = multiple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_warn_setting.lower_limit
     *
     * @return the value of gas_warn_setting.lower_limit
     *
     * @mbg.generated
     */
    public Double getLowerLimit() {
        return lowerLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_warn_setting.lower_limit
     *
     * @param lowerLimit the value for gas_warn_setting.lower_limit
     *
     * @mbg.generated
     */
    public void setLowerLimit(Double lowerLimit) {
        this.lowerLimit = lowerLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_warn_setting.upper_limit
     *
     * @return the value of gas_warn_setting.upper_limit
     *
     * @mbg.generated
     */
    public Double getUpperLimit() {
        return upperLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_warn_setting.upper_limit
     *
     * @param upperLimit the value for gas_warn_setting.upper_limit
     *
     * @mbg.generated
     */
    public void setUpperLimit(Double upperLimit) {
        this.upperLimit = upperLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_warn_setting.lower_continued_time
     *
     * @return the value of gas_warn_setting.lower_continued_time
     *
     * @mbg.generated
     */
    public Integer getLowerContinuedTime() {
        return lowerContinuedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_warn_setting.lower_continued_time
     *
     * @param lowerContinuedTime the value for gas_warn_setting.lower_continued_time
     *
     * @mbg.generated
     */
    public void setLowerContinuedTime(Integer lowerContinuedTime) {
        this.lowerContinuedTime = lowerContinuedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_warn_setting.upper_continued_time
     *
     * @return the value of gas_warn_setting.upper_continued_time
     *
     * @mbg.generated
     */
    public Integer getUpperContinuedTime() {
        return upperContinuedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_warn_setting.upper_continued_time
     *
     * @param upperContinuedTime the value for gas_warn_setting.upper_continued_time
     *
     * @mbg.generated
     */
    public void setUpperContinuedTime(Integer upperContinuedTime) {
        this.upperContinuedTime = upperContinuedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gas_warn_setting.standard_id
     *
     * @return the value of gas_warn_setting.standard_id
     *
     * @mbg.generated
     */
    public Integer getStandardId() {
        return standardId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gas_warn_setting.standard_id
     *
     * @param standardId the value for gas_warn_setting.standard_id
     *
     * @mbg.generated
     */
    public void setStandardId(Integer standardId) {
        this.standardId = standardId;
    }
}
