package com.cst.xinhe.persistence.model.warn_level;

public class LevelData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column level_data.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column level_data.level_name
     *
     * @mbg.generated
     */
    private String levelName;

    //后补
    private Integer rangSettingId;

    public Integer getRangSettingId() {
        return rangSettingId;
    }

    public void setRangSettingId(Integer rangSettingId) {
        this.rangSettingId = rangSettingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column level_data.id
     *
     * @return the value of level_data.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column level_data.id
     *
     * @param id the value for level_data.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column level_data.level_name
     *
     * @return the value of level_data.level_name
     *
     * @mbg.generated
     */
    public String getLevelName() {
        return levelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column level_data.level_name
     *
     * @param levelName the value for level_data.level_name
     *
     * @mbg.generated
     */
    public void setLevelName(String levelName) {
        this.levelName = levelName == null ? null : levelName.trim();
    }
}
