package com.cst.xinhe.persistence.model.warning_area;

import com.alibaba.fastjson.annotation.JSONField;

import java.util.Date;

public class WarningArea {

    private boolean counter;

    private Integer  staffNum;

    public Integer getStaffNum() {
        return staffNum;
    }

    public void setStaffNum(Integer staffNum) {
        this.staffNum = staffNum;
    }

    public boolean isCounter() {
        return counter;
    }

    public void setCounter(boolean counter) {
        this.counter = counter;
    }


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning_area.warning_area_id
     *
     * @mbg.generated
     */
    private Integer warningAreaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning_area.warning_area_name
     *
     * @mbg.generated
     */

    private String warningAreaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning_area.warning_area_desc
     *
     * @mbg.generated
     */
    private String warningAreaDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning_area.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning_area.warning_area_type
     *
     * @mbg.generated
     */
    private Integer warningAreaType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning_area.residence_time
     *
     * @mbg.generated
     */
    private String residenceTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning_area.contain_number
     *
     * @mbg.generated
     */
    private Integer containNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning_area.warning_area_id
     *
     * @return the value of warning_area.warning_area_id
     *
     * @mbg.generated
     */
    public Integer getWarningAreaId() {
        return warningAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning_area.warning_area_id
     *
     * @param warningAreaId the value for warning_area.warning_area_id
     *
     * @mbg.generated
     */
    public void setWarningAreaId(Integer warningAreaId) {
        this.warningAreaId = warningAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning_area.warning_area_name
     *
     * @return the value of warning_area.warning_area_name
     *
     * @mbg.generated
     */
    public String getWarningAreaName() {
        return warningAreaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning_area.warning_area_name
     *
     * @param warningAreaName the value for warning_area.warning_area_name
     *
     * @mbg.generated
     */
    public void setWarningAreaName(String warningAreaName) {
        this.warningAreaName = warningAreaName == null ? null : warningAreaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning_area.warning_area_desc
     *
     * @return the value of warning_area.warning_area_desc
     *
     * @mbg.generated
     */
    public String getWarningAreaDesc() {
        return warningAreaDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning_area.warning_area_desc
     *
     * @param warningAreaDesc the value for warning_area.warning_area_desc
     *
     * @mbg.generated
     */
    public void setWarningAreaDesc(String warningAreaDesc) {
        this.warningAreaDesc = warningAreaDesc == null ? null : warningAreaDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning_area.create_time
     *
     * @return the value of warning_area.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning_area.create_time
     *
     * @param createTime the value for warning_area.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning_area.warning_area_type
     *
     * @return the value of warning_area.warning_area_type
     *
     * @mbg.generated
     */
    public Integer getWarningAreaType() {
        return warningAreaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning_area.warning_area_type
     *
     * @param warningAreaType the value for warning_area.warning_area_type
     *
     * @mbg.generated
     */
    public void setWarningAreaType(Integer warningAreaType) {
        this.warningAreaType = warningAreaType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning_area.residence_time
     *
     * @return the value of warning_area.residence_time
     *
     * @mbg.generated
     */
    public String getResidenceTime() {
        return residenceTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning_area.residence_time
     *
     * @param residenceTime the value for warning_area.residence_time
     *
     * @mbg.generated
     */
    public void setResidenceTime(String residenceTime) {
        this.residenceTime = residenceTime == null ? null : residenceTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning_area.contain_number
     *
     * @return the value of warning_area.contain_number
     *
     * @mbg.generated
     */
    public Integer getContainNumber() {
        return containNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning_area.contain_number
     *
     * @param containNumber the value for warning_area.contain_number
     *
     * @mbg.generated
     */
    public void setContainNumber(Integer containNumber) {
        this.containNumber = containNumber;
    }
}
