package com.cst.xinhe.persistence.model.warning_area;

import java.util.Date;

public class WarningAreaRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning_area_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning_area_record.warning_area_id
     *
     * @mbg.generated
     */
    private Integer warningAreaId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning_area_record.in_time
     *
     * @mbg.generated
     */
    private Date inTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning_area_record.out_time
     *
     * @mbg.generated
     */
    private Date outTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column warning_area_record.staff_id
     *
     * @mbg.generated
     */
    private Integer staffId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning_area_record.id
     *
     * @return the value of warning_area_record.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning_area_record.id
     *
     * @param id the value for warning_area_record.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning_area_record.warning_area_id
     *
     * @return the value of warning_area_record.warning_area_id
     *
     * @mbg.generated
     */
    public Integer getWarningAreaId() {
        return warningAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning_area_record.warning_area_id
     *
     * @param warningAreaId the value for warning_area_record.warning_area_id
     *
     * @mbg.generated
     */
    public void setWarningAreaId(Integer warningAreaId) {
        this.warningAreaId = warningAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning_area_record.in_time
     *
     * @return the value of warning_area_record.in_time
     *
     * @mbg.generated
     */
    public Date getInTime() {
        return inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning_area_record.in_time
     *
     * @param inTime the value for warning_area_record.in_time
     *
     * @mbg.generated
     */
    public void setInTime(Date inTime) {
        this.inTime = inTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning_area_record.out_time
     *
     * @return the value of warning_area_record.out_time
     *
     * @mbg.generated
     */
    public Date getOutTime() {
        return outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning_area_record.out_time
     *
     * @param outTime the value for warning_area_record.out_time
     *
     * @mbg.generated
     */
    public void setOutTime(Date outTime) {
        this.outTime = outTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column warning_area_record.staff_id
     *
     * @return the value of warning_area_record.staff_id
     *
     * @mbg.generated
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column warning_area_record.staff_id
     *
     * @param staffId the value for warning_area_record.staff_id
     *
     * @mbg.generated
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    @Override
    public String toString() {
        return "WarningAreaRecord{" +
                "id=" + id +
                ", warningAreaId=" + warningAreaId +
                ", inTime=" + inTime +
                ", outTime=" + outTime +
                ", staffId=" + staffId +
                '}';
    }
}
