package com.cst.xinhe.persistence.model.coordinate;

public class Coordinate {


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coordinate.coordinate_id
     *
     * @mbg.generated
     */
    private Integer coordinateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coordinate.coordinate_x
     *
     * @mbg.generated
     */
    private Double coordinateX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coordinate.coordinate_y
     *
     * @mbg.generated
     */
    private Double coordinateY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coordinate.coordinate_z
     *
     * @mbg.generated
     */
    private Double coordinateZ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coordinate.warning_area_id
     *
     * @mbg.generated
     */
    private Integer warningAreaId;

    private String warningAreaName;
    private Integer warning_area_type;

    public Integer getWarning_area_type() {
        return warning_area_type;
    }

    public void setWarning_area_type(Integer warning_area_type) {
        this.warning_area_type = warning_area_type;
    }

    public String getWarningAreaName() {
        return warningAreaName;
    }

    public void setWarningAreaName(String warningAreaName) {
        this.warningAreaName = warningAreaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coordinate.coordinate_id
     *
     * @return the value of coordinate.coordinate_id
     *
     * @mbg.generated
     */
    public Integer getCoordinateId() {
        return coordinateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coordinate.coordinate_id
     *
     * @param coordinateId the value for coordinate.coordinate_id
     *
     * @mbg.generated
     */
    public void setCoordinateId(Integer coordinateId) {
        this.coordinateId = coordinateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coordinate.coordinate_x
     *
     * @return the value of coordinate.coordinate_x
     *
     * @mbg.generated
     */
    public Double getCoordinateX() {
        return coordinateX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coordinate.coordinate_x
     *
     * @param coordinateX the value for coordinate.coordinate_x
     *
     * @mbg.generated
     */
    public void setCoordinateX(Double coordinateX) {
        this.coordinateX = coordinateX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coordinate.coordinate_y
     *
     * @return the value of coordinate.coordinate_y
     *
     * @mbg.generated
     */
    public Double getCoordinateY() {
        return coordinateY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coordinate.coordinate_y
     *
     * @param coordinateY the value for coordinate.coordinate_y
     *
     * @mbg.generated
     */
    public void setCoordinateY(Double coordinateY) {
        this.coordinateY = coordinateY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coordinate.coordinate_z
     *
     * @return the value of coordinate.coordinate_z
     *
     * @mbg.generated
     */
    public Double getCoordinateZ() {
        return coordinateZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coordinate.coordinate_z
     *
     * @param coordinateZ the value for coordinate.coordinate_z
     *
     * @mbg.generated
     */
    public void setCoordinateZ(Double coordinateZ) {
        this.coordinateZ = coordinateZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coordinate.warning_area_id
     *
     * @return the value of coordinate.warning_area_id
     *
     * @mbg.generated
     */
    public Integer getWarningAreaId() {
        return warningAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coordinate.warning_area_id
     *
     * @param warningAreaId the value for coordinate.warning_area_id
     *
     * @mbg.generated
     */
    public void setWarningAreaId(Integer warningAreaId) {
        this.warningAreaId = warningAreaId;
    }
}
