spring:
  application:
    name: station-monitor-server
netty:
  port: 7777
server:
  port: 8765
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
feign:
  hystrix:
    enabled: true #熔断器hystrix
#打印日志
logging:
  level:
    #org.springframework.web: DEBUG
    com.cst.xinhe.persistence.dao: DEBUG
  config: classpath:logback-boot.xml
