package com.cst.xinhe.persistence.model.chat;

import java.util.Date;

public class TemporarySendList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temporary_send_list.temporary_send_list_id
     *
     * @mbg.generated
     */
    private Integer temporarySendListId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temporary_send_list.voice_url
     *
     * @mbg.generated
     */
    private String voiceUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temporary_send_list.terminal_id
     *
     * @mbg.generated
     */
    private Integer terminalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temporary_send_list.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temporary_send_list.real_time
     *
     * @mbg.generated
     */
    private Date realTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temporary_send_list.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temporary_send_list.temporary_send_list_id
     *
     * @return the value of temporary_send_list.temporary_send_list_id
     *
     * @mbg.generated
     */
    public Integer getTemporarySendListId() {
        return temporarySendListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temporary_send_list.temporary_send_list_id
     *
     * @param temporarySendListId the value for temporary_send_list.temporary_send_list_id
     *
     * @mbg.generated
     */
    public void setTemporarySendListId(Integer temporarySendListId) {
        this.temporarySendListId = temporarySendListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temporary_send_list.voice_url
     *
     * @return the value of temporary_send_list.voice_url
     *
     * @mbg.generated
     */
    public String getVoiceUrl() {
        return voiceUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temporary_send_list.voice_url
     *
     * @param voiceUrl the value for temporary_send_list.voice_url
     *
     * @mbg.generated
     */
    public void setVoiceUrl(String voiceUrl) {
        this.voiceUrl = voiceUrl == null ? null : voiceUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temporary_send_list.terminal_id
     *
     * @return the value of temporary_send_list.terminal_id
     *
     * @mbg.generated
     */
    public Integer getTerminalId() {
        return terminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temporary_send_list.terminal_id
     *
     * @param terminalId the value for temporary_send_list.terminal_id
     *
     * @mbg.generated
     */
    public void setTerminalId(Integer terminalId) {
        this.terminalId = terminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temporary_send_list.create_time
     *
     * @return the value of temporary_send_list.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temporary_send_list.create_time
     *
     * @param createTime the value for temporary_send_list.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temporary_send_list.real_time
     *
     * @return the value of temporary_send_list.real_time
     *
     * @mbg.generated
     */
    public Date getRealTime() {
        return realTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temporary_send_list.real_time
     *
     * @param realTime the value for temporary_send_list.real_time
     *
     * @mbg.generated
     */
    public void setRealTime(Date realTime) {
        this.realTime = realTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temporary_send_list.type
     *
     * @return the value of temporary_send_list.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temporary_send_list.type
     *
     * @param type the value for temporary_send_list.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }
}