package com.cst.xinhe.persistence.dao.malfunction;

import com.cst.xinhe.persistence.model.malfunction.Malfunction;
import com.cst.xinhe.persistence.model.malfunction.MalfunctionExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface MalfunctionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malfunction
     *
     * @mbg.generated
     */
    long countByExample(MalfunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malfunction
     *
     * @mbg.generated
     */
    int deleteByExample(MalfunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malfunction
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer selfCheckId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malfunction
     *
     * @mbg.generated
     */
    int insert(Malfunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malfunction
     *
     * @mbg.generated
     */
    int insertSelective(Malfunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malfunction
     *
     * @mbg.generated
     */
    List<Malfunction> selectByExample(MalfunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malfunction
     *
     * @mbg.generated
     */
    Malfunction selectByPrimaryKey(Integer selfCheckId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malfunction
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Malfunction record, @Param("example") MalfunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malfunction
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Malfunction record, @Param("example") MalfunctionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malfunction
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Malfunction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table malfunction
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Malfunction record);

    Map<String, Object> selectCountMalfunction();

    List<Malfunction> selectMalfunction(@Param("status") Integer status, @Param("terminalId") Integer terminalId);
}
