server:
  port: 8762
  ssl:
    key-store: zkxh.keystore
    #密钥库密码
    key-store-password: 123456
    keyStoreType: JKS
    keyAlias: zkxh
    enabled: true
eureka:
  server:
    peer-node-read-timeout-ms: 1000
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  instance:
    hostname: eureka
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: https://127.0.0.1:8761/eureka/
#打印日志
logging:
  level:
    #org.springframework.web: DEBUG
    com.cst.xinhe.persistence.dao: DEBUG
  config: classpath:logback-boot.xml
