package com.cst.xinhe.persistence.dao.updateIp;

import com.cst.xinhe.persistence.model.updateIp.TerminalIpPort;
import com.cst.xinhe.persistence.model.updateIp.TerminalIpPortExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TerminalIpPortMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_ip_port
     *
     * @mbg.generated
     */
    long countByExample(TerminalIpPortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_ip_port
     *
     * @mbg.generated
     */
    int deleteByExample(TerminalIpPortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_ip_port
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer terminalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_ip_port
     *
     * @mbg.generated
     */
    int insert(TerminalIpPort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_ip_port
     *
     * @mbg.generated
     */
    int insertSelective(TerminalIpPort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_ip_port
     *
     * @mbg.generated
     */
    List<TerminalIpPort> selectByExample(TerminalIpPortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_ip_port
     *
     * @mbg.generated
     */
    TerminalIpPort selectByPrimaryKey(Integer terminalId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_ip_port
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TerminalIpPort record, @Param("example") TerminalIpPortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_ip_port
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TerminalIpPort record, @Param("example") TerminalIpPortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_ip_port
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TerminalIpPort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table terminal_ip_port
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TerminalIpPort record);

    Integer findTerminalIdByIpPort(@Param("terminalIp") String terminalIp, @Param("port") int port);
}
