package com.cst.xinhe.persistence.dao.staff_terminal_relation;

import com.cst.xinhe.persistence.model.staff_terminal_relation.StaffTerminalRelation;
import com.cst.xinhe.persistence.model.staff_terminal_relation.StaffTerminalRelationExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface StaffTerminalRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_terminal_relation
     *
     * @mbg.generated
     */
    long countByExample(StaffTerminalRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_terminal_relation
     *
     * @mbg.generated
     */
    int deleteByExample(StaffTerminalRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_terminal_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer staffTerminalRelationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_terminal_relation
     *
     * @mbg.generated
     */
    int insert(StaffTerminalRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_terminal_relation
     *
     * @mbg.generated
     */
    int insertSelective(StaffTerminalRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_terminal_relation
     *
     * @mbg.generated
     */
    List<StaffTerminalRelation> selectByExample(StaffTerminalRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_terminal_relation
     *
     * @mbg.generated
     */
    StaffTerminalRelation selectByPrimaryKey(Integer staffTerminalRelationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_terminal_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StaffTerminalRelation record, @Param("example") StaffTerminalRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_terminal_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StaffTerminalRelation record, @Param("example") StaffTerminalRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_terminal_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StaffTerminalRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table staff_terminal_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StaffTerminalRelation record);

    List<StaffTerminalRelation> findNewRelationByParams(Map<String, Object> map);

}
