package com.cst.xinhe.persistence.dao.warning_area;

import com.cst.xinhe.persistence.model.warning_area.WarningAreaRecord;
import com.cst.xinhe.persistence.model.warning_area.WarningAreaRecordExample;
import org.apache.ibatis.annotations.Param;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

public interface WarningAreaRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warning_area_record
     *
     * @mbg.generated
     */
    long countByExample(WarningAreaRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warning_area_record
     *
     * @mbg.generated
     */
    int deleteByExample(WarningAreaRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warning_area_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warning_area_record
     *
     * @mbg.generated
     */
    int insert(WarningAreaRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warning_area_record
     *
     * @mbg.generated
     */
    int insertSelective(WarningAreaRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warning_area_record
     *
     * @mbg.generated
     */
    List<WarningAreaRecord> selectByExample(WarningAreaRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warning_area_record
     *
     * @mbg.generated
     */
    WarningAreaRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warning_area_record
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") WarningAreaRecord record, @Param("example") WarningAreaRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warning_area_record
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") WarningAreaRecord record, @Param("example") WarningAreaRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warning_area_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(WarningAreaRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table warning_area_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(WarningAreaRecord record);

    List<HashMap<String,Object>> findAreaRecordByAreaId(@Param("areaIdList") Set<Integer> areaIdList, @Param("staffName") String staffName, @Param("deptIds") List<Integer> deptIds);

    List<HashMap<String,Object>> findHistoryAreaRecord(@Param("areaId") Integer areaId, @Param("staffName") String staffName, @Param("deptIds") List<Integer> deptIds);

    List<HashMap<String,Object>> findAreaRecordByStaffId(@Param("type") Integer type, @Param("areaId") Integer areaId, @Param("staffId") Integer staffId);


    Integer findStaffNumByAreaId(Integer id);

    Integer findStaffNumByType(@Param("type") Integer type);


    List<WarningAreaRecord> findWarningAreaRecordByStaffAndOutTime(Integer staffId);

//    Integer selectWarningPersonCountByTypeAndTime(Map<String, Object> param);

    List<Map<String, Object>> getWarningWarePersonNumber(Map<String, Object> param);
}
