package com.cst.xinhe.persistence.model.wechat;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class WxUserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_user
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_user
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wx_user
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated
     */
    public WxUserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wx_user
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wx_user
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWxUserIdIsNull() {
            addCriterion("wx_user_id is null");
            return (Criteria) this;
        }

        public Criteria andWxUserIdIsNotNull() {
            addCriterion("wx_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andWxUserIdEqualTo(Integer value) {
            addCriterion("wx_user_id =", value, "wxUserId");
            return (Criteria) this;
        }

        public Criteria andWxUserIdNotEqualTo(Integer value) {
            addCriterion("wx_user_id <>", value, "wxUserId");
            return (Criteria) this;
        }

        public Criteria andWxUserIdGreaterThan(Integer value) {
            addCriterion("wx_user_id >", value, "wxUserId");
            return (Criteria) this;
        }

        public Criteria andWxUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("wx_user_id >=", value, "wxUserId");
            return (Criteria) this;
        }

        public Criteria andWxUserIdLessThan(Integer value) {
            addCriterion("wx_user_id <", value, "wxUserId");
            return (Criteria) this;
        }

        public Criteria andWxUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("wx_user_id <=", value, "wxUserId");
            return (Criteria) this;
        }

        public Criteria andWxUserIdIn(List<Integer> values) {
            addCriterion("wx_user_id in", values, "wxUserId");
            return (Criteria) this;
        }

        public Criteria andWxUserIdNotIn(List<Integer> values) {
            addCriterion("wx_user_id not in", values, "wxUserId");
            return (Criteria) this;
        }

        public Criteria andWxUserIdBetween(Integer value1, Integer value2) {
            addCriterion("wx_user_id between", value1, value2, "wxUserId");
            return (Criteria) this;
        }

        public Criteria andWxUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("wx_user_id not between", value1, value2, "wxUserId");
            return (Criteria) this;
        }

        public Criteria andWxUserAccountIsNull() {
            addCriterion("wx_user_account is null");
            return (Criteria) this;
        }

        public Criteria andWxUserAccountIsNotNull() {
            addCriterion("wx_user_account is not null");
            return (Criteria) this;
        }

        public Criteria andWxUserAccountEqualTo(String value) {
            addCriterion("wx_user_account =", value, "wxUserAccount");
            return (Criteria) this;
        }

        public Criteria andWxUserAccountNotEqualTo(String value) {
            addCriterion("wx_user_account <>", value, "wxUserAccount");
            return (Criteria) this;
        }

        public Criteria andWxUserAccountGreaterThan(String value) {
            addCriterion("wx_user_account >", value, "wxUserAccount");
            return (Criteria) this;
        }

        public Criteria andWxUserAccountGreaterThanOrEqualTo(String value) {
            addCriterion("wx_user_account >=", value, "wxUserAccount");
            return (Criteria) this;
        }

        public Criteria andWxUserAccountLessThan(String value) {
            addCriterion("wx_user_account <", value, "wxUserAccount");
            return (Criteria) this;
        }

        public Criteria andWxUserAccountLessThanOrEqualTo(String value) {
            addCriterion("wx_user_account <=", value, "wxUserAccount");
            return (Criteria) this;
        }

        public Criteria andWxUserAccountLike(String value) {
            addCriterion("wx_user_account like", value, "wxUserAccount");
            return (Criteria) this;
        }

        public Criteria andWxUserAccountNotLike(String value) {
            addCriterion("wx_user_account not like", value, "wxUserAccount");
            return (Criteria) this;
        }

        public Criteria andWxUserAccountIn(List<String> values) {
            addCriterion("wx_user_account in", values, "wxUserAccount");
            return (Criteria) this;
        }

        public Criteria andWxUserAccountNotIn(List<String> values) {
            addCriterion("wx_user_account not in", values, "wxUserAccount");
            return (Criteria) this;
        }

        public Criteria andWxUserAccountBetween(String value1, String value2) {
            addCriterion("wx_user_account between", value1, value2, "wxUserAccount");
            return (Criteria) this;
        }

        public Criteria andWxUserAccountNotBetween(String value1, String value2) {
            addCriterion("wx_user_account not between", value1, value2, "wxUserAccount");
            return (Criteria) this;
        }

        public Criteria andWxUserPasswordIsNull() {
            addCriterion("wx_user_password is null");
            return (Criteria) this;
        }

        public Criteria andWxUserPasswordIsNotNull() {
            addCriterion("wx_user_password is not null");
            return (Criteria) this;
        }

        public Criteria andWxUserPasswordEqualTo(String value) {
            addCriterion("wx_user_password =", value, "wxUserPassword");
            return (Criteria) this;
        }

        public Criteria andWxUserPasswordNotEqualTo(String value) {
            addCriterion("wx_user_password <>", value, "wxUserPassword");
            return (Criteria) this;
        }

        public Criteria andWxUserPasswordGreaterThan(String value) {
            addCriterion("wx_user_password >", value, "wxUserPassword");
            return (Criteria) this;
        }

        public Criteria andWxUserPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("wx_user_password >=", value, "wxUserPassword");
            return (Criteria) this;
        }

        public Criteria andWxUserPasswordLessThan(String value) {
            addCriterion("wx_user_password <", value, "wxUserPassword");
            return (Criteria) this;
        }

        public Criteria andWxUserPasswordLessThanOrEqualTo(String value) {
            addCriterion("wx_user_password <=", value, "wxUserPassword");
            return (Criteria) this;
        }

        public Criteria andWxUserPasswordLike(String value) {
            addCriterion("wx_user_password like", value, "wxUserPassword");
            return (Criteria) this;
        }

        public Criteria andWxUserPasswordNotLike(String value) {
            addCriterion("wx_user_password not like", value, "wxUserPassword");
            return (Criteria) this;
        }

        public Criteria andWxUserPasswordIn(List<String> values) {
            addCriterion("wx_user_password in", values, "wxUserPassword");
            return (Criteria) this;
        }

        public Criteria andWxUserPasswordNotIn(List<String> values) {
            addCriterion("wx_user_password not in", values, "wxUserPassword");
            return (Criteria) this;
        }

        public Criteria andWxUserPasswordBetween(String value1, String value2) {
            addCriterion("wx_user_password between", value1, value2, "wxUserPassword");
            return (Criteria) this;
        }

        public Criteria andWxUserPasswordNotBetween(String value1, String value2) {
            addCriterion("wx_user_password not between", value1, value2, "wxUserPassword");
            return (Criteria) this;
        }

        public Criteria andSendMsgFlagIsNull() {
            addCriterion("send_msg_flag is null");
            return (Criteria) this;
        }

        public Criteria andSendMsgFlagIsNotNull() {
            addCriterion("send_msg_flag is not null");
            return (Criteria) this;
        }

        public Criteria andSendMsgFlagEqualTo(Integer value) {
            addCriterion("send_msg_flag =", value, "sendMsgFlag");
            return (Criteria) this;
        }

        public Criteria andSendMsgFlagNotEqualTo(Integer value) {
            addCriterion("send_msg_flag <>", value, "sendMsgFlag");
            return (Criteria) this;
        }

        public Criteria andSendMsgFlagGreaterThan(Integer value) {
            addCriterion("send_msg_flag >", value, "sendMsgFlag");
            return (Criteria) this;
        }

        public Criteria andSendMsgFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("send_msg_flag >=", value, "sendMsgFlag");
            return (Criteria) this;
        }

        public Criteria andSendMsgFlagLessThan(Integer value) {
            addCriterion("send_msg_flag <", value, "sendMsgFlag");
            return (Criteria) this;
        }

        public Criteria andSendMsgFlagLessThanOrEqualTo(Integer value) {
            addCriterion("send_msg_flag <=", value, "sendMsgFlag");
            return (Criteria) this;
        }

        public Criteria andSendMsgFlagIn(List<Integer> values) {
            addCriterion("send_msg_flag in", values, "sendMsgFlag");
            return (Criteria) this;
        }

        public Criteria andSendMsgFlagNotIn(List<Integer> values) {
            addCriterion("send_msg_flag not in", values, "sendMsgFlag");
            return (Criteria) this;
        }

        public Criteria andSendMsgFlagBetween(Integer value1, Integer value2) {
            addCriterion("send_msg_flag between", value1, value2, "sendMsgFlag");
            return (Criteria) this;
        }

        public Criteria andSendMsgFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("send_msg_flag not between", value1, value2, "sendMsgFlag");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andStaffIdIsNull() {
            addCriterion("staff_id is null");
            return (Criteria) this;
        }

        public Criteria andStaffIdIsNotNull() {
            addCriterion("staff_id is not null");
            return (Criteria) this;
        }

        public Criteria andStaffIdEqualTo(Integer value) {
            addCriterion("staff_id =", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotEqualTo(Integer value) {
            addCriterion("staff_id <>", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdGreaterThan(Integer value) {
            addCriterion("staff_id >", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("staff_id >=", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdLessThan(Integer value) {
            addCriterion("staff_id <", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdLessThanOrEqualTo(Integer value) {
            addCriterion("staff_id <=", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdIn(List<Integer> values) {
            addCriterion("staff_id in", values, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotIn(List<Integer> values) {
            addCriterion("staff_id not in", values, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdBetween(Integer value1, Integer value2) {
            addCriterion("staff_id between", value1, value2, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotBetween(Integer value1, Integer value2) {
            addCriterion("staff_id not between", value1, value2, "staffId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wx_user
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table wx_user
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}