server:
  port: 8769
spring:
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
    active: native
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
