package com.cst.xinhe.persistence.dao.station_standard_relation;

import com.cst.xinhe.persistence.model.station_standard_relation.StationStandardRelation;
import com.cst.xinhe.persistence.model.station_standard_relation.StationStandardRelationExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface StationStandardRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_standard_relation
     *
     * @mbg.generated
     */
    long countByExample(StationStandardRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_standard_relation
     *
     * @mbg.generated
     */
    int deleteByExample(StationStandardRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_standard_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer stationStandardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_standard_relation
     *
     * @mbg.generated
     */
    int insert(StationStandardRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_standard_relation
     *
     * @mbg.generated
     */
    int insertSelective(StationStandardRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_standard_relation
     *
     * @mbg.generated
     */
    List<StationStandardRelation> selectByExample(StationStandardRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_standard_relation
     *
     * @mbg.generated
     */
    StationStandardRelation selectByPrimaryKey(Integer stationStandardId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_standard_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") StationStandardRelation record, @Param("example") StationStandardRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_standard_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") StationStandardRelation record, @Param("example") StationStandardRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_standard_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StationStandardRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station_standard_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StationStandardRelation record);

    StationStandardRelation selectStandardByStationId(Integer stationId);
}
