package com.cst.xinhe.persistence.model.staff;


import java.util.List;

public class StaffOrganization {

    private Integer id;

    private String name;


    private Integer parentId;

    private Integer sort;

    private String type;

    private List<StaffOrganization> children;
    private String label;


    public List<StaffOrganization> getChildren() {
        return children;
    }

    public void setChildren(List<StaffOrganization> children) {
        this.children = children;
    }

    public String getLabel() {
        return label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_organization.id
     *
     * @param id the value for staff_organization.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_organization.name
     *
     * @return the value of staff_organization.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_organization.name
     *
     * @param name the value for staff_organization.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_organization.parent_id
     *
     * @return the value of staff_organization.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_organization.parent_id
     *
     * @param parentId the value for staff_organization.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_organization.sort
     *
     * @return the value of staff_organization.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_organization.sort
     *
     * @param sort the value for staff_organization.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_organization.type
     *
     * @return the value of staff_organization.type
     *
     * @mbg.generated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_organization.type
     *
     * @param type the value for staff_organization.type
     *
     * @mbg.generated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}
