package com.cst.xinhe.persistence.dao.base_station;

import com.cst.xinhe.persistence.model.base_station.OfflineStation;
import com.cst.xinhe.persistence.model.base_station.OfflineStationExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface OfflineStationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_station
     *
     * @mbg.generated
     */
    long countByExample(OfflineStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_station
     *
     * @mbg.generated
     */
    int deleteByExample(OfflineStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_station
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer offlineStationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_station
     *
     * @mbg.generated
     */
    int insert(OfflineStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_station
     *
     * @mbg.generated
     */
    int insertSelective(OfflineStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_station
     *
     * @mbg.generated
     */
    List<OfflineStation> selectByExample(OfflineStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_station
     *
     * @mbg.generated
     */
    OfflineStation selectByPrimaryKey(Integer offlineStationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_station
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OfflineStation record, @Param("example") OfflineStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_station
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OfflineStation record, @Param("example") OfflineStationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_station
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OfflineStation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table offline_station
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(OfflineStation record);

    List<Map<String, Object>> selectOfflineStation(Map<String, Object> params);

    List<Map<String, Object>> selectOfflineStationPartitionIdsNotNull(Map<String, Object> params);

    List<Map<String, Object>> selectOfflineStationPartitionIdsIsNull(Map<String, Object> params);
}
