management:
  endpoints:
    web:
      exposure:
        include: '*'
    health:
      sensitive: false #关闭过滤敏感信息
  endpoint:
    health:
      show-details: ALWAYS
spring:
  elasticsearch:
    rest:
      uris: ["http://192.168.1.188:9200"]
  boot:
    admin:
      client:
        url: http://127.0.0.1:5000
  application:
    name: kafka-sender-service
  kafka:
    partition-number: 3
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      bootstrap-servers: 192.168.1.188:9092
    consumer:
      group-id: test
      max-poll-records: 1000
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 1000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      bootstrap-servers: 192.168.1.188:9092
    listener:
      concurrency: 4
server:
  port: 8768
eureka:
  instance:
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
    health-check-url-path: /actuator/health
    instance-id: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
#feign:
#  hystrix:
#    enabled: true
