package com.cst.xinhe.persistence.model.base_station;

import java.util.Date;

public class OfflineStation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_station.offline_station_id
     *
     * @mbg.generated
     */
    private Integer offlineStationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column offline_station.offline_time
     *
     * @mbg.generated
     */
    private Date offlineTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_station.offline_station_id
     *
     * @return the value of offline_station.offline_station_id
     *
     * @mbg.generated
     */
    public Integer getOfflineStationId() {
        return offlineStationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_station.offline_station_id
     *
     * @param offlineStationId the value for offline_station.offline_station_id
     *
     * @mbg.generated
     */
    public void setOfflineStationId(Integer offlineStationId) {
        this.offlineStationId = offlineStationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column offline_station.offline_time
     *
     * @return the value of offline_station.offline_time
     *
     * @mbg.generated
     */
    public Date getOfflineTime() {
        return offlineTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column offline_station.offline_time
     *
     * @param offlineTime the value for offline_station.offline_time
     *
     * @mbg.generated
     */
    public void setOfflineTime(Date offlineTime) {
        this.offlineTime = offlineTime;
    }
}
