package com.cst.xinhe.persistence.model.attendance;

import java.util.Date;

public class StaffAttendanceRealRule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_attendance_real_rule.staff_id
     *
     * @mbg.generated
     */
    private Integer staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_attendance_real_rule.real_rule_start_time
     *
     * @mbg.generated
     */
    private Date realRuleStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_attendance_real_rule.real_rule_end_time
     *
     * @mbg.generated
     */
    private Date realRuleEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_attendance_real_rule.is_over_time
     *
     * @mbg.generated
     */
    private Integer isOverTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_attendance_real_rule.is_serious_time
     *
     * @mbg.generated
     */
    private Integer isSeriousTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_attendance_real_rule.final_time
     *
     * @mbg.generated
     */
    private Date finalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column staff_attendance_real_rule.is_attendance
     *
     * @mbg.generated
     */
    private Integer isAttendance;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_attendance_real_rule.staff_id
     *
     * @return the value of staff_attendance_real_rule.staff_id
     *
     * @mbg.generated
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_attendance_real_rule.staff_id
     *
     * @param staffId the value for staff_attendance_real_rule.staff_id
     *
     * @mbg.generated
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_attendance_real_rule.real_rule_start_time
     *
     * @return the value of staff_attendance_real_rule.real_rule_start_time
     *
     * @mbg.generated
     */
    public Date getRealRuleStartTime() {
        return realRuleStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_attendance_real_rule.real_rule_start_time
     *
     * @param realRuleStartTime the value for staff_attendance_real_rule.real_rule_start_time
     *
     * @mbg.generated
     */
    public void setRealRuleStartTime(Date realRuleStartTime) {
        this.realRuleStartTime = realRuleStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_attendance_real_rule.real_rule_end_time
     *
     * @return the value of staff_attendance_real_rule.real_rule_end_time
     *
     * @mbg.generated
     */
    public Date getRealRuleEndTime() {
        return realRuleEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_attendance_real_rule.real_rule_end_time
     *
     * @param realRuleEndTime the value for staff_attendance_real_rule.real_rule_end_time
     *
     * @mbg.generated
     */
    public void setRealRuleEndTime(Date realRuleEndTime) {
        this.realRuleEndTime = realRuleEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_attendance_real_rule.is_over_time
     *
     * @return the value of staff_attendance_real_rule.is_over_time
     *
     * @mbg.generated
     */
    public Integer getIsOverTime() {
        return isOverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_attendance_real_rule.is_over_time
     *
     * @param isOverTime the value for staff_attendance_real_rule.is_over_time
     *
     * @mbg.generated
     */
    public void setIsOverTime(Integer isOverTime) {
        this.isOverTime = isOverTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_attendance_real_rule.is_serious_time
     *
     * @return the value of staff_attendance_real_rule.is_serious_time
     *
     * @mbg.generated
     */
    public Integer getIsSeriousTime() {
        return isSeriousTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_attendance_real_rule.is_serious_time
     *
     * @param isSeriousTime the value for staff_attendance_real_rule.is_serious_time
     *
     * @mbg.generated
     */
    public void setIsSeriousTime(Integer isSeriousTime) {
        this.isSeriousTime = isSeriousTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_attendance_real_rule.final_time
     *
     * @return the value of staff_attendance_real_rule.final_time
     *
     * @mbg.generated
     */
    public Date getFinalTime() {
        return finalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_attendance_real_rule.final_time
     *
     * @param finalTime the value for staff_attendance_real_rule.final_time
     *
     * @mbg.generated
     */
    public void setFinalTime(Date finalTime) {
        this.finalTime = finalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column staff_attendance_real_rule.is_attendance
     *
     * @return the value of staff_attendance_real_rule.is_attendance
     *
     * @mbg.generated
     */
    public Integer getIsAttendance() {
        return isAttendance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column staff_attendance_real_rule.is_attendance
     *
     * @param isAttendance the value for staff_attendance_real_rule.is_attendance
     *
     * @mbg.generated
     */
    public void setIsAttendance(Integer isAttendance) {
        this.isAttendance = isAttendance;
    }
}
