package com.cst.xinhe.persistence.model.attendance;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class TimeStandardExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    public TimeStandardExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCTime(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Time> timeList = new ArrayList<java.sql.Time>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                timeList.add(new java.sql.Time(iter.next().getTime()));
            }
            addCriterion(condition, timeList, property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value1.getTime()), new java.sql.Time(value2.getTime()), property);
        }

        public Criteria andTimeStandardIdIsNull() {
            addCriterion("time_standard_id is null");
            return (Criteria) this;
        }

        public Criteria andTimeStandardIdIsNotNull() {
            addCriterion("time_standard_id is not null");
            return (Criteria) this;
        }

        public Criteria andTimeStandardIdEqualTo(Integer value) {
            addCriterion("time_standard_id =", value, "timeStandardId");
            return (Criteria) this;
        }

        public Criteria andTimeStandardIdNotEqualTo(Integer value) {
            addCriterion("time_standard_id <>", value, "timeStandardId");
            return (Criteria) this;
        }

        public Criteria andTimeStandardIdGreaterThan(Integer value) {
            addCriterion("time_standard_id >", value, "timeStandardId");
            return (Criteria) this;
        }

        public Criteria andTimeStandardIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("time_standard_id >=", value, "timeStandardId");
            return (Criteria) this;
        }

        public Criteria andTimeStandardIdLessThan(Integer value) {
            addCriterion("time_standard_id <", value, "timeStandardId");
            return (Criteria) this;
        }

        public Criteria andTimeStandardIdLessThanOrEqualTo(Integer value) {
            addCriterion("time_standard_id <=", value, "timeStandardId");
            return (Criteria) this;
        }

        public Criteria andTimeStandardIdIn(List<Integer> values) {
            addCriterion("time_standard_id in", values, "timeStandardId");
            return (Criteria) this;
        }

        public Criteria andTimeStandardIdNotIn(List<Integer> values) {
            addCriterion("time_standard_id not in", values, "timeStandardId");
            return (Criteria) this;
        }

        public Criteria andTimeStandardIdBetween(Integer value1, Integer value2) {
            addCriterion("time_standard_id between", value1, value2, "timeStandardId");
            return (Criteria) this;
        }

        public Criteria andTimeStandardIdNotBetween(Integer value1, Integer value2) {
            addCriterion("time_standard_id not between", value1, value2, "timeStandardId");
            return (Criteria) this;
        }

        public Criteria andTimeStandardNameIsNull() {
            addCriterion("time_standard_name is null");
            return (Criteria) this;
        }

        public Criteria andTimeStandardNameIsNotNull() {
            addCriterion("time_standard_name is not null");
            return (Criteria) this;
        }

        public Criteria andTimeStandardNameEqualTo(String value) {
            addCriterion("time_standard_name =", value, "timeStandardName");
            return (Criteria) this;
        }

        public Criteria andTimeStandardNameNotEqualTo(String value) {
            addCriterion("time_standard_name <>", value, "timeStandardName");
            return (Criteria) this;
        }

        public Criteria andTimeStandardNameGreaterThan(String value) {
            addCriterion("time_standard_name >", value, "timeStandardName");
            return (Criteria) this;
        }

        public Criteria andTimeStandardNameGreaterThanOrEqualTo(String value) {
            addCriterion("time_standard_name >=", value, "timeStandardName");
            return (Criteria) this;
        }

        public Criteria andTimeStandardNameLessThan(String value) {
            addCriterion("time_standard_name <", value, "timeStandardName");
            return (Criteria) this;
        }

        public Criteria andTimeStandardNameLessThanOrEqualTo(String value) {
            addCriterion("time_standard_name <=", value, "timeStandardName");
            return (Criteria) this;
        }

        public Criteria andTimeStandardNameLike(String value) {
            addCriterion("time_standard_name like", value, "timeStandardName");
            return (Criteria) this;
        }

        public Criteria andTimeStandardNameNotLike(String value) {
            addCriterion("time_standard_name not like", value, "timeStandardName");
            return (Criteria) this;
        }

        public Criteria andTimeStandardNameIn(List<String> values) {
            addCriterion("time_standard_name in", values, "timeStandardName");
            return (Criteria) this;
        }

        public Criteria andTimeStandardNameNotIn(List<String> values) {
            addCriterion("time_standard_name not in", values, "timeStandardName");
            return (Criteria) this;
        }

        public Criteria andTimeStandardNameBetween(String value1, String value2) {
            addCriterion("time_standard_name between", value1, value2, "timeStandardName");
            return (Criteria) this;
        }

        public Criteria andTimeStandardNameNotBetween(String value1, String value2) {
            addCriterion("time_standard_name not between", value1, value2, "timeStandardName");
            return (Criteria) this;
        }

        public Criteria andTimeStandardDescIsNull() {
            addCriterion("time_standard_desc is null");
            return (Criteria) this;
        }

        public Criteria andTimeStandardDescIsNotNull() {
            addCriterion("time_standard_desc is not null");
            return (Criteria) this;
        }

        public Criteria andTimeStandardDescEqualTo(String value) {
            addCriterion("time_standard_desc =", value, "timeStandardDesc");
            return (Criteria) this;
        }

        public Criteria andTimeStandardDescNotEqualTo(String value) {
            addCriterion("time_standard_desc <>", value, "timeStandardDesc");
            return (Criteria) this;
        }

        public Criteria andTimeStandardDescGreaterThan(String value) {
            addCriterion("time_standard_desc >", value, "timeStandardDesc");
            return (Criteria) this;
        }

        public Criteria andTimeStandardDescGreaterThanOrEqualTo(String value) {
            addCriterion("time_standard_desc >=", value, "timeStandardDesc");
            return (Criteria) this;
        }

        public Criteria andTimeStandardDescLessThan(String value) {
            addCriterion("time_standard_desc <", value, "timeStandardDesc");
            return (Criteria) this;
        }

        public Criteria andTimeStandardDescLessThanOrEqualTo(String value) {
            addCriterion("time_standard_desc <=", value, "timeStandardDesc");
            return (Criteria) this;
        }

        public Criteria andTimeStandardDescLike(String value) {
            addCriterion("time_standard_desc like", value, "timeStandardDesc");
            return (Criteria) this;
        }

        public Criteria andTimeStandardDescNotLike(String value) {
            addCriterion("time_standard_desc not like", value, "timeStandardDesc");
            return (Criteria) this;
        }

        public Criteria andTimeStandardDescIn(List<String> values) {
            addCriterion("time_standard_desc in", values, "timeStandardDesc");
            return (Criteria) this;
        }

        public Criteria andTimeStandardDescNotIn(List<String> values) {
            addCriterion("time_standard_desc not in", values, "timeStandardDesc");
            return (Criteria) this;
        }

        public Criteria andTimeStandardDescBetween(String value1, String value2) {
            addCriterion("time_standard_desc between", value1, value2, "timeStandardDesc");
            return (Criteria) this;
        }

        public Criteria andTimeStandardDescNotBetween(String value1, String value2) {
            addCriterion("time_standard_desc not between", value1, value2, "timeStandardDesc");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNull() {
            addCriterion("start_time is null");
            return (Criteria) this;
        }

        public Criteria andStartTimeIsNotNull() {
            addCriterion("start_time is not null");
            return (Criteria) this;
        }

        public Criteria andStartTimeEqualTo(Date value) {
            addCriterionForJDBCTime("start_time =", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotEqualTo(Date value) {
            addCriterionForJDBCTime("start_time <>", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThan(Date value) {
            addCriterionForJDBCTime("start_time >", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("start_time >=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThan(Date value) {
            addCriterionForJDBCTime("start_time <", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("start_time <=", value, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeIn(List<Date> values) {
            addCriterionForJDBCTime("start_time in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotIn(List<Date> values) {
            addCriterionForJDBCTime("start_time not in", values, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("start_time between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andStartTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("start_time not between", value1, value2, "startTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterionForJDBCTime("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterionForJDBCTime("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterionForJDBCTime("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterionForJDBCTime("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterionForJDBCTime("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterionForJDBCTime("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andElasticTimeIsNull() {
            addCriterion("elastic_time is null");
            return (Criteria) this;
        }

        public Criteria andElasticTimeIsNotNull() {
            addCriterion("elastic_time is not null");
            return (Criteria) this;
        }

        public Criteria andElasticTimeEqualTo(Integer value) {
            addCriterion("elastic_time =", value, "elasticTime");
            return (Criteria) this;
        }

        public Criteria andElasticTimeNotEqualTo(Integer value) {
            addCriterion("elastic_time <>", value, "elasticTime");
            return (Criteria) this;
        }

        public Criteria andElasticTimeGreaterThan(Integer value) {
            addCriterion("elastic_time >", value, "elasticTime");
            return (Criteria) this;
        }

        public Criteria andElasticTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("elastic_time >=", value, "elasticTime");
            return (Criteria) this;
        }

        public Criteria andElasticTimeLessThan(Integer value) {
            addCriterion("elastic_time <", value, "elasticTime");
            return (Criteria) this;
        }

        public Criteria andElasticTimeLessThanOrEqualTo(Integer value) {
            addCriterion("elastic_time <=", value, "elasticTime");
            return (Criteria) this;
        }

        public Criteria andElasticTimeIn(List<Integer> values) {
            addCriterion("elastic_time in", values, "elasticTime");
            return (Criteria) this;
        }

        public Criteria andElasticTimeNotIn(List<Integer> values) {
            addCriterion("elastic_time not in", values, "elasticTime");
            return (Criteria) this;
        }

        public Criteria andElasticTimeBetween(Integer value1, Integer value2) {
            addCriterion("elastic_time between", value1, value2, "elasticTime");
            return (Criteria) this;
        }

        public Criteria andElasticTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("elastic_time not between", value1, value2, "elasticTime");
            return (Criteria) this;
        }

        public Criteria andLateTimeIsNull() {
            addCriterion("late_time is null");
            return (Criteria) this;
        }

        public Criteria andLateTimeIsNotNull() {
            addCriterion("late_time is not null");
            return (Criteria) this;
        }

        public Criteria andLateTimeEqualTo(Integer value) {
            addCriterion("late_time =", value, "lateTime");
            return (Criteria) this;
        }

        public Criteria andLateTimeNotEqualTo(Integer value) {
            addCriterion("late_time <>", value, "lateTime");
            return (Criteria) this;
        }

        public Criteria andLateTimeGreaterThan(Integer value) {
            addCriterion("late_time >", value, "lateTime");
            return (Criteria) this;
        }

        public Criteria andLateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("late_time >=", value, "lateTime");
            return (Criteria) this;
        }

        public Criteria andLateTimeLessThan(Integer value) {
            addCriterion("late_time <", value, "lateTime");
            return (Criteria) this;
        }

        public Criteria andLateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("late_time <=", value, "lateTime");
            return (Criteria) this;
        }

        public Criteria andLateTimeIn(List<Integer> values) {
            addCriterion("late_time in", values, "lateTime");
            return (Criteria) this;
        }

        public Criteria andLateTimeNotIn(List<Integer> values) {
            addCriterion("late_time not in", values, "lateTime");
            return (Criteria) this;
        }

        public Criteria andLateTimeBetween(Integer value1, Integer value2) {
            addCriterion("late_time between", value1, value2, "lateTime");
            return (Criteria) this;
        }

        public Criteria andLateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("late_time not between", value1, value2, "lateTime");
            return (Criteria) this;
        }

        public Criteria andSeriousLateTimeIsNull() {
            addCriterion("serious_late_time is null");
            return (Criteria) this;
        }

        public Criteria andSeriousLateTimeIsNotNull() {
            addCriterion("serious_late_time is not null");
            return (Criteria) this;
        }

        public Criteria andSeriousLateTimeEqualTo(Integer value) {
            addCriterion("serious_late_time =", value, "seriousLateTime");
            return (Criteria) this;
        }

        public Criteria andSeriousLateTimeNotEqualTo(Integer value) {
            addCriterion("serious_late_time <>", value, "seriousLateTime");
            return (Criteria) this;
        }

        public Criteria andSeriousLateTimeGreaterThan(Integer value) {
            addCriterion("serious_late_time >", value, "seriousLateTime");
            return (Criteria) this;
        }

        public Criteria andSeriousLateTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("serious_late_time >=", value, "seriousLateTime");
            return (Criteria) this;
        }

        public Criteria andSeriousLateTimeLessThan(Integer value) {
            addCriterion("serious_late_time <", value, "seriousLateTime");
            return (Criteria) this;
        }

        public Criteria andSeriousLateTimeLessThanOrEqualTo(Integer value) {
            addCriterion("serious_late_time <=", value, "seriousLateTime");
            return (Criteria) this;
        }

        public Criteria andSeriousLateTimeIn(List<Integer> values) {
            addCriterion("serious_late_time in", values, "seriousLateTime");
            return (Criteria) this;
        }

        public Criteria andSeriousLateTimeNotIn(List<Integer> values) {
            addCriterion("serious_late_time not in", values, "seriousLateTime");
            return (Criteria) this;
        }

        public Criteria andSeriousLateTimeBetween(Integer value1, Integer value2) {
            addCriterion("serious_late_time between", value1, value2, "seriousLateTime");
            return (Criteria) this;
        }

        public Criteria andSeriousLateTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("serious_late_time not between", value1, value2, "seriousLateTime");
            return (Criteria) this;
        }

        public Criteria andLeaveEarlyTimeIsNull() {
            addCriterion("leave_early_time is null");
            return (Criteria) this;
        }

        public Criteria andLeaveEarlyTimeIsNotNull() {
            addCriterion("leave_early_time is not null");
            return (Criteria) this;
        }

        public Criteria andLeaveEarlyTimeEqualTo(Integer value) {
            addCriterion("leave_early_time =", value, "leaveEarlyTime");
            return (Criteria) this;
        }

        public Criteria andLeaveEarlyTimeNotEqualTo(Integer value) {
            addCriterion("leave_early_time <>", value, "leaveEarlyTime");
            return (Criteria) this;
        }

        public Criteria andLeaveEarlyTimeGreaterThan(Integer value) {
            addCriterion("leave_early_time >", value, "leaveEarlyTime");
            return (Criteria) this;
        }

        public Criteria andLeaveEarlyTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("leave_early_time >=", value, "leaveEarlyTime");
            return (Criteria) this;
        }

        public Criteria andLeaveEarlyTimeLessThan(Integer value) {
            addCriterion("leave_early_time <", value, "leaveEarlyTime");
            return (Criteria) this;
        }

        public Criteria andLeaveEarlyTimeLessThanOrEqualTo(Integer value) {
            addCriterion("leave_early_time <=", value, "leaveEarlyTime");
            return (Criteria) this;
        }

        public Criteria andLeaveEarlyTimeIn(List<Integer> values) {
            addCriterion("leave_early_time in", values, "leaveEarlyTime");
            return (Criteria) this;
        }

        public Criteria andLeaveEarlyTimeNotIn(List<Integer> values) {
            addCriterion("leave_early_time not in", values, "leaveEarlyTime");
            return (Criteria) this;
        }

        public Criteria andLeaveEarlyTimeBetween(Integer value1, Integer value2) {
            addCriterion("leave_early_time between", value1, value2, "leaveEarlyTime");
            return (Criteria) this;
        }

        public Criteria andLeaveEarlyTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("leave_early_time not between", value1, value2, "leaveEarlyTime");
            return (Criteria) this;
        }

        public Criteria andSeriousLeaveEarlyTimeIsNull() {
            addCriterion("serious_leave_early_time is null");
            return (Criteria) this;
        }

        public Criteria andSeriousLeaveEarlyTimeIsNotNull() {
            addCriterion("serious_leave_early_time is not null");
            return (Criteria) this;
        }

        public Criteria andSeriousLeaveEarlyTimeEqualTo(Integer value) {
            addCriterion("serious_leave_early_time =", value, "seriousLeaveEarlyTime");
            return (Criteria) this;
        }

        public Criteria andSeriousLeaveEarlyTimeNotEqualTo(Integer value) {
            addCriterion("serious_leave_early_time <>", value, "seriousLeaveEarlyTime");
            return (Criteria) this;
        }

        public Criteria andSeriousLeaveEarlyTimeGreaterThan(Integer value) {
            addCriterion("serious_leave_early_time >", value, "seriousLeaveEarlyTime");
            return (Criteria) this;
        }

        public Criteria andSeriousLeaveEarlyTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("serious_leave_early_time >=", value, "seriousLeaveEarlyTime");
            return (Criteria) this;
        }

        public Criteria andSeriousLeaveEarlyTimeLessThan(Integer value) {
            addCriterion("serious_leave_early_time <", value, "seriousLeaveEarlyTime");
            return (Criteria) this;
        }

        public Criteria andSeriousLeaveEarlyTimeLessThanOrEqualTo(Integer value) {
            addCriterion("serious_leave_early_time <=", value, "seriousLeaveEarlyTime");
            return (Criteria) this;
        }

        public Criteria andSeriousLeaveEarlyTimeIn(List<Integer> values) {
            addCriterion("serious_leave_early_time in", values, "seriousLeaveEarlyTime");
            return (Criteria) this;
        }

        public Criteria andSeriousLeaveEarlyTimeNotIn(List<Integer> values) {
            addCriterion("serious_leave_early_time not in", values, "seriousLeaveEarlyTime");
            return (Criteria) this;
        }

        public Criteria andSeriousLeaveEarlyTimeBetween(Integer value1, Integer value2) {
            addCriterion("serious_leave_early_time between", value1, value2, "seriousLeaveEarlyTime");
            return (Criteria) this;
        }

        public Criteria andSeriousLeaveEarlyTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("serious_leave_early_time not between", value1, value2, "seriousLeaveEarlyTime");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andFlagIsNull() {
            addCriterion("flag is null");
            return (Criteria) this;
        }

        public Criteria andFlagIsNotNull() {
            addCriterion("flag is not null");
            return (Criteria) this;
        }

        public Criteria andFlagEqualTo(Integer value) {
            addCriterion("flag =", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotEqualTo(Integer value) {
            addCriterion("flag <>", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThan(Integer value) {
            addCriterion("flag >", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagGreaterThanOrEqualTo(Integer value) {
            addCriterion("flag >=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThan(Integer value) {
            addCriterion("flag <", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagLessThanOrEqualTo(Integer value) {
            addCriterion("flag <=", value, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagIn(List<Integer> values) {
            addCriterion("flag in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotIn(List<Integer> values) {
            addCriterion("flag not in", values, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagBetween(Integer value1, Integer value2) {
            addCriterion("flag between", value1, value2, "flag");
            return (Criteria) this;
        }

        public Criteria andFlagNotBetween(Integer value1, Integer value2) {
            addCriterion("flag not between", value1, value2, "flag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table time_standard
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table time_standard
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
