package com.cst.xinhe.persistence.dao.e_msg;

import com.cst.xinhe.persistence.model.e_msg.ExceptionMessage;
import com.cst.xinhe.persistence.model.e_msg.ExceptionMessageExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface ExceptionMessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_message
     *
     * @mbg.generated
     */
    long countByExample(ExceptionMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_message
     *
     * @mbg.generated
     */
    int deleteByExample(ExceptionMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_message
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long eMsgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_message
     *
     * @mbg.generated
     */
    int insert(ExceptionMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_message
     *
     * @mbg.generated
     */
    int insertSelective(ExceptionMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_message
     *
     * @mbg.generated
     */
    List<ExceptionMessage> selectByExample(ExceptionMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_message
     *
     * @mbg.generated
     */
    ExceptionMessage selectByPrimaryKey(Long eMsgId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_message
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ExceptionMessage record, @Param("example") ExceptionMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_message
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ExceptionMessage record, @Param("example") ExceptionMessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ExceptionMessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exception_message
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ExceptionMessage record);

    List<Map<String, Object>> selectByParams(Map<String, Object> params);
}
