package com.cst.xinhe.persistence.model.e_call;

import java.util.Date;

public class ECall {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.e_call_id
     *
     * @mbg.generated
     */
    private Long eCallId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.co
     *
     * @mbg.generated
     */
    private Double co;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.co_unit
     *
     * @mbg.generated
     */
    private Integer coUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.ch4
     *
     * @mbg.generated
     */
    private Double ch4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.ch4_unit
     *
     * @mbg.generated
     */
    private Integer ch4Unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.o2
     *
     * @mbg.generated
     */
    private Double o2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.o2_unit
     *
     * @mbg.generated
     */
    private Integer o2Unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.co2
     *
     * @mbg.generated
     */
    private Double co2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.co2_unit
     *
     * @mbg.generated
     */
    private Integer co2Unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.temperature
     *
     * @mbg.generated
     */
    private Double temperature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.temperature_unit
     *
     * @mbg.generated
     */
    private Integer temperatureUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.humidity
     *
     * @mbg.generated
     */
    private Double humidity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.humidity_unit
     *
     * @mbg.generated
     */
    private Integer humidityUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.field_3
     *
     * @mbg.generated
     */
    private Double field3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.field_3_unit
     *
     * @mbg.generated
     */
    private Integer field3Unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.staff_id
     *
     * @mbg.generated
     */
    private Integer staffId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.terminal_id
     *
     * @mbg.generated
     */
    private Integer terminalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.station_id
     *
     * @mbg.generated
     */
    private Integer stationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.terminal_ip
     *
     * @mbg.generated
     */
    private String terminalIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.station_ip
     *
     * @mbg.generated
     */
    private String stationIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.terminal_real_time
     *
     * @mbg.generated
     */
    private Date terminalRealTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.info_type
     *
     * @mbg.generated
     */
    private Integer infoType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.sequence_id
     *
     * @mbg.generated
     */
    private Integer sequenceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.position_x
     *
     * @mbg.generated
     */
    private Double positionX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.position_y
     *
     * @mbg.generated
     */
    private Double positionY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.position_z
     *
     * @mbg.generated
     */
    private Double positionZ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.station_id1
     *
     * @mbg.generated
     */
    private Integer stationId1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.station_id2
     *
     * @mbg.generated
     */
    private Integer stationId2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.wifi_strength1
     *
     * @mbg.generated
     */
    private Double wifiStrength1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.wifi_strength2
     *
     * @mbg.generated
     */
    private Double wifiStrength2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.temp_position_name
     *
     * @mbg.generated
     */
    private String tempPositionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.is_ore
     *
     * @mbg.generated
     */
    private Integer isOre;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column e_call.gas_flag
     *
     * @mbg.generated
     */
    private Integer gasFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.e_call_id
     *
     * @return the value of e_call.e_call_id
     *
     * @mbg.generated
     */
    public Long geteCallId() {
        return eCallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.e_call_id
     *
     * @param eCallId the value for e_call.e_call_id
     *
     * @mbg.generated
     */
    public void seteCallId(Long eCallId) {
        this.eCallId = eCallId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.co
     *
     * @return the value of e_call.co
     *
     * @mbg.generated
     */
    public Double getCo() {
        return co;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.co
     *
     * @param co the value for e_call.co
     *
     * @mbg.generated
     */
    public void setCo(Double co) {
        this.co = co;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.co_unit
     *
     * @return the value of e_call.co_unit
     *
     * @mbg.generated
     */
    public Integer getCoUnit() {
        return coUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.co_unit
     *
     * @param coUnit the value for e_call.co_unit
     *
     * @mbg.generated
     */
    public void setCoUnit(Integer coUnit) {
        this.coUnit = coUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.ch4
     *
     * @return the value of e_call.ch4
     *
     * @mbg.generated
     */
    public Double getCh4() {
        return ch4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.ch4
     *
     * @param ch4 the value for e_call.ch4
     *
     * @mbg.generated
     */
    public void setCh4(Double ch4) {
        this.ch4 = ch4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.ch4_unit
     *
     * @return the value of e_call.ch4_unit
     *
     * @mbg.generated
     */
    public Integer getCh4Unit() {
        return ch4Unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.ch4_unit
     *
     * @param ch4Unit the value for e_call.ch4_unit
     *
     * @mbg.generated
     */
    public void setCh4Unit(Integer ch4Unit) {
        this.ch4Unit = ch4Unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.o2
     *
     * @return the value of e_call.o2
     *
     * @mbg.generated
     */
    public Double getO2() {
        return o2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.o2
     *
     * @param o2 the value for e_call.o2
     *
     * @mbg.generated
     */
    public void setO2(Double o2) {
        this.o2 = o2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.o2_unit
     *
     * @return the value of e_call.o2_unit
     *
     * @mbg.generated
     */
    public Integer getO2Unit() {
        return o2Unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.o2_unit
     *
     * @param o2Unit the value for e_call.o2_unit
     *
     * @mbg.generated
     */
    public void setO2Unit(Integer o2Unit) {
        this.o2Unit = o2Unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.co2
     *
     * @return the value of e_call.co2
     *
     * @mbg.generated
     */
    public Double getCo2() {
        return co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.co2
     *
     * @param co2 the value for e_call.co2
     *
     * @mbg.generated
     */
    public void setCo2(Double co2) {
        this.co2 = co2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.co2_unit
     *
     * @return the value of e_call.co2_unit
     *
     * @mbg.generated
     */
    public Integer getCo2Unit() {
        return co2Unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.co2_unit
     *
     * @param co2Unit the value for e_call.co2_unit
     *
     * @mbg.generated
     */
    public void setCo2Unit(Integer co2Unit) {
        this.co2Unit = co2Unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.temperature
     *
     * @return the value of e_call.temperature
     *
     * @mbg.generated
     */
    public Double getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.temperature
     *
     * @param temperature the value for e_call.temperature
     *
     * @mbg.generated
     */
    public void setTemperature(Double temperature) {
        this.temperature = temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.temperature_unit
     *
     * @return the value of e_call.temperature_unit
     *
     * @mbg.generated
     */
    public Integer getTemperatureUnit() {
        return temperatureUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.temperature_unit
     *
     * @param temperatureUnit the value for e_call.temperature_unit
     *
     * @mbg.generated
     */
    public void setTemperatureUnit(Integer temperatureUnit) {
        this.temperatureUnit = temperatureUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.humidity
     *
     * @return the value of e_call.humidity
     *
     * @mbg.generated
     */
    public Double getHumidity() {
        return humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.humidity
     *
     * @param humidity the value for e_call.humidity
     *
     * @mbg.generated
     */
    public void setHumidity(Double humidity) {
        this.humidity = humidity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.humidity_unit
     *
     * @return the value of e_call.humidity_unit
     *
     * @mbg.generated
     */
    public Integer getHumidityUnit() {
        return humidityUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.humidity_unit
     *
     * @param humidityUnit the value for e_call.humidity_unit
     *
     * @mbg.generated
     */
    public void setHumidityUnit(Integer humidityUnit) {
        this.humidityUnit = humidityUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.field_3
     *
     * @return the value of e_call.field_3
     *
     * @mbg.generated
     */
    public Double getField3() {
        return field3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.field_3
     *
     * @param field3 the value for e_call.field_3
     *
     * @mbg.generated
     */
    public void setField3(Double field3) {
        this.field3 = field3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.field_3_unit
     *
     * @return the value of e_call.field_3_unit
     *
     * @mbg.generated
     */
    public Integer getField3Unit() {
        return field3Unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.field_3_unit
     *
     * @param field3Unit the value for e_call.field_3_unit
     *
     * @mbg.generated
     */
    public void setField3Unit(Integer field3Unit) {
        this.field3Unit = field3Unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.staff_id
     *
     * @return the value of e_call.staff_id
     *
     * @mbg.generated
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.staff_id
     *
     * @param staffId the value for e_call.staff_id
     *
     * @mbg.generated
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.terminal_id
     *
     * @return the value of e_call.terminal_id
     *
     * @mbg.generated
     */
    public Integer getTerminalId() {
        return terminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.terminal_id
     *
     * @param terminalId the value for e_call.terminal_id
     *
     * @mbg.generated
     */
    public void setTerminalId(Integer terminalId) {
        this.terminalId = terminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.station_id
     *
     * @return the value of e_call.station_id
     *
     * @mbg.generated
     */
    public Integer getStationId() {
        return stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.station_id
     *
     * @param stationId the value for e_call.station_id
     *
     * @mbg.generated
     */
    public void setStationId(Integer stationId) {
        this.stationId = stationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.terminal_ip
     *
     * @return the value of e_call.terminal_ip
     *
     * @mbg.generated
     */
    public String getTerminalIp() {
        return terminalIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.terminal_ip
     *
     * @param terminalIp the value for e_call.terminal_ip
     *
     * @mbg.generated
     */
    public void setTerminalIp(String terminalIp) {
        this.terminalIp = terminalIp == null ? null : terminalIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.station_ip
     *
     * @return the value of e_call.station_ip
     *
     * @mbg.generated
     */
    public String getStationIp() {
        return stationIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.station_ip
     *
     * @param stationIp the value for e_call.station_ip
     *
     * @mbg.generated
     */
    public void setStationIp(String stationIp) {
        this.stationIp = stationIp == null ? null : stationIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.terminal_real_time
     *
     * @return the value of e_call.terminal_real_time
     *
     * @mbg.generated
     */
    public Date getTerminalRealTime() {
        return terminalRealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.terminal_real_time
     *
     * @param terminalRealTime the value for e_call.terminal_real_time
     *
     * @mbg.generated
     */
    public void setTerminalRealTime(Date terminalRealTime) {
        this.terminalRealTime = terminalRealTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.info_type
     *
     * @return the value of e_call.info_type
     *
     * @mbg.generated
     */
    public Integer getInfoType() {
        return infoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.info_type
     *
     * @param infoType the value for e_call.info_type
     *
     * @mbg.generated
     */
    public void setInfoType(Integer infoType) {
        this.infoType = infoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.sequence_id
     *
     * @return the value of e_call.sequence_id
     *
     * @mbg.generated
     */
    public Integer getSequenceId() {
        return sequenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.sequence_id
     *
     * @param sequenceId the value for e_call.sequence_id
     *
     * @mbg.generated
     */
    public void setSequenceId(Integer sequenceId) {
        this.sequenceId = sequenceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.position_x
     *
     * @return the value of e_call.position_x
     *
     * @mbg.generated
     */
    public Double getPositionX() {
        return positionX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.position_x
     *
     * @param positionX the value for e_call.position_x
     *
     * @mbg.generated
     */
    public void setPositionX(Double positionX) {
        this.positionX = positionX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.position_y
     *
     * @return the value of e_call.position_y
     *
     * @mbg.generated
     */
    public Double getPositionY() {
        return positionY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.position_y
     *
     * @param positionY the value for e_call.position_y
     *
     * @mbg.generated
     */
    public void setPositionY(Double positionY) {
        this.positionY = positionY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.position_z
     *
     * @return the value of e_call.position_z
     *
     * @mbg.generated
     */
    public Double getPositionZ() {
        return positionZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.position_z
     *
     * @param positionZ the value for e_call.position_z
     *
     * @mbg.generated
     */
    public void setPositionZ(Double positionZ) {
        this.positionZ = positionZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.station_id1
     *
     * @return the value of e_call.station_id1
     *
     * @mbg.generated
     */
    public Integer getStationId1() {
        return stationId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.station_id1
     *
     * @param stationId1 the value for e_call.station_id1
     *
     * @mbg.generated
     */
    public void setStationId1(Integer stationId1) {
        this.stationId1 = stationId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.station_id2
     *
     * @return the value of e_call.station_id2
     *
     * @mbg.generated
     */
    public Integer getStationId2() {
        return stationId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.station_id2
     *
     * @param stationId2 the value for e_call.station_id2
     *
     * @mbg.generated
     */
    public void setStationId2(Integer stationId2) {
        this.stationId2 = stationId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.wifi_strength1
     *
     * @return the value of e_call.wifi_strength1
     *
     * @mbg.generated
     */
    public Double getWifiStrength1() {
        return wifiStrength1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.wifi_strength1
     *
     * @param wifiStrength1 the value for e_call.wifi_strength1
     *
     * @mbg.generated
     */
    public void setWifiStrength1(Double wifiStrength1) {
        this.wifiStrength1 = wifiStrength1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.wifi_strength2
     *
     * @return the value of e_call.wifi_strength2
     *
     * @mbg.generated
     */
    public Double getWifiStrength2() {
        return wifiStrength2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.wifi_strength2
     *
     * @param wifiStrength2 the value for e_call.wifi_strength2
     *
     * @mbg.generated
     */
    public void setWifiStrength2(Double wifiStrength2) {
        this.wifiStrength2 = wifiStrength2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.create_time
     *
     * @return the value of e_call.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.create_time
     *
     * @param createTime the value for e_call.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.temp_position_name
     *
     * @return the value of e_call.temp_position_name
     *
     * @mbg.generated
     */
    public String getTempPositionName() {
        return tempPositionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.temp_position_name
     *
     * @param tempPositionName the value for e_call.temp_position_name
     *
     * @mbg.generated
     */
    public void setTempPositionName(String tempPositionName) {
        this.tempPositionName = tempPositionName == null ? null : tempPositionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.is_ore
     *
     * @return the value of e_call.is_ore
     *
     * @mbg.generated
     */
    public Integer getIsOre() {
        return isOre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.is_ore
     *
     * @param isOre the value for e_call.is_ore
     *
     * @mbg.generated
     */
    public void setIsOre(Integer isOre) {
        this.isOre = isOre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column e_call.gas_flag
     *
     * @return the value of e_call.gas_flag
     *
     * @mbg.generated
     */
    public Integer getGasFlag() {
        return gasFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column e_call.gas_flag
     *
     * @param gasFlag the value for e_call.gas_flag
     *
     * @mbg.generated
     */
    public void setGasFlag(Integer gasFlag) {
        this.gasFlag = gasFlag;
    }
}