server:
  port: 8761
eureka:
  server:
    peer-node-read-timeout-ms: 1000
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
    use-read-only-response-cache: false
    renewal-percent-threshold: 0.85
  instance:
    hostname: eureka
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://192.168.1.101:8762/eureka/
#打印日志
logging:
  level:
    #org.springframework.web: DEBUG
    com.cst.xinhe.persistence.dao: DEBUG
  config: classpath:logback-boot.xml
