package com.cst.xinhe.persistence.model.terminal_road;


import com.cst.xinhe.persistence.vo.req.StaffInfoVO;

import java.util.Date;

public class TerminalRoad {

    private StaffInfoVO staffInfoVO;

    public StaffInfoVO getStaffInfoVO() {
        return staffInfoVO;
    }

    public void setStaffInfoVO(StaffInfoVO staffInfoVO) {
        this.staffInfoVO = staffInfoVO;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_road.terminal_road_id
     *
     * @mbg.generated
     */
    private Integer terminalRoadId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_road.staff_terminal_id
     *
     * @mbg.generated
     */
    private Integer staffTerminalId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_road.position_x
     *
     * @mbg.generated
     */
    private Double positionX;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_road.position_y
     *
     * @mbg.generated
     */
    private Double positionY;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_road.position_z
     *
     * @mbg.generated
     */
    private Double positionZ;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_road.station_id1
     *
     * @mbg.generated
     */
    private Integer stationId1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_road.station_id2
     *
     * @mbg.generated
     */
    private Integer stationId2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_road.wifi_strength1
     *
     * @mbg.generated
     */
    private Double wifiStrength1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_road.wifi_strength2
     *
     * @mbg.generated
     */
    private Double wifiStrength2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_road.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column terminal_road.temp_position_name
     *
     * @mbg.generated
     */
    private String tempPositionName;

    //后补
    private Integer staffId;
    private Integer isOre;
    private Integer stationId;

    public Integer getStationId() {
        return stationId;
    }

    public void setStationId(Integer stationId) {
        this.stationId = stationId;
    }

    public Integer getIsOre() {
        return isOre;
    }

    public void setIsOre(Integer isOre) {
        this.isOre = isOre;
    }

    public Integer getStaffId() {
        return staffId;
    }

    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_road.terminal_road_id
     *
     * @return the value of terminal_road.terminal_road_id
     * @mbg.generated
     */
    public Integer getTerminalRoadId() {
        return terminalRoadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_road.terminal_road_id
     *
     * @param terminalRoadId the value for terminal_road.terminal_road_id
     * @mbg.generated
     */
    public void setTerminalRoadId(Integer terminalRoadId) {
        this.terminalRoadId = terminalRoadId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_road.staff_terminal_id
     *
     * @return the value of terminal_road.staff_terminal_id
     * @mbg.generated
     */
    public Integer getStaffTerminalId() {
        return staffTerminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_road.staff_terminal_id
     *
     * @param staffTerminalId the value for terminal_road.staff_terminal_id
     * @mbg.generated
     */
    public void setStaffTerminalId(Integer staffTerminalId) {
        this.staffTerminalId = staffTerminalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_road.position_x
     *
     * @return the value of terminal_road.position_x
     * @mbg.generated
     */
    public Double getPositionX() {
        return positionX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_road.position_x
     *
     * @param positionX the value for terminal_road.position_x
     * @mbg.generated
     */
    public void setPositionX(Double positionX) {
        this.positionX = positionX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_road.position_y
     *
     * @return the value of terminal_road.position_y
     * @mbg.generated
     */
    public Double getPositionY() {
        return positionY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_road.position_y
     *
     * @param positionY the value for terminal_road.position_y
     * @mbg.generated
     */
    public void setPositionY(Double positionY) {
        this.positionY = positionY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_road.position_z
     *
     * @return the value of terminal_road.position_z
     * @mbg.generated
     */
    public Double getPositionZ() {
        return positionZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_road.position_z
     *
     * @param positionZ the value for terminal_road.position_z
     * @mbg.generated
     */
    public void setPositionZ(Double positionZ) {
        this.positionZ = positionZ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_road.station_id1
     *
     * @return the value of terminal_road.station_id1
     * @mbg.generated
     */
    public Integer getStationId1() {
        return stationId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_road.station_id1
     *
     * @param stationId1 the value for terminal_road.station_id1
     * @mbg.generated
     */
    public void setStationId1(Integer stationId1) {
        this.stationId1 = stationId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_road.station_id2
     *
     * @return the value of terminal_road.station_id2
     * @mbg.generated
     */
    public Integer getStationId2() {
        return stationId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_road.station_id2
     *
     * @param stationId2 the value for terminal_road.station_id2
     * @mbg.generated
     */
    public void setStationId2(Integer stationId2) {
        this.stationId2 = stationId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_road.wifi_strength1
     *
     * @return the value of terminal_road.wifi_strength1
     * @mbg.generated
     */
    public Double getWifiStrength1() {
        return wifiStrength1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_road.wifi_strength1
     *
     * @param wifiStrength1 the value for terminal_road.wifi_strength1
     * @mbg.generated
     */
    public void setWifiStrength1(Double wifiStrength1) {
        this.wifiStrength1 = wifiStrength1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_road.wifi_strength2
     *
     * @return the value of terminal_road.wifi_strength2
     * @mbg.generated
     */
    public Double getWifiStrength2() {
        return wifiStrength2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_road.wifi_strength2
     *
     * @param wifiStrength2 the value for terminal_road.wifi_strength2
     * @mbg.generated
     */
    public void setWifiStrength2(Double wifiStrength2) {
        this.wifiStrength2 = wifiStrength2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_road.createTime
     *
     * @return the value of terminal_road.createTime
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_road.createTime
     *
     * @param createtime the value for terminal_road.createTime
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column terminal_road.temp_position_name
     *
     * @return the value of terminal_road.temp_position_name
     * @mbg.generated
     */
    public String getTempPositionName() {
        return tempPositionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column terminal_road.temp_position_name
     *
     * @param tempPositionName the value for terminal_road.temp_position_name
     * @mbg.generated
     */
    public void setTempPositionName(String tempPositionName) {
        this.tempPositionName = tempPositionName == null ? null : tempPositionName.trim();
    }

    @Override
    public String toString() {
        return "TerminalRoad{" +
                "staffInfoVO=" + staffInfoVO +
                ", terminalRoadId=" + terminalRoadId +
                ", staffTerminalId=" + staffTerminalId +
                ", positionX=" + positionX +
                ", positionY=" + positionY +
                ", positionZ=" + positionZ +
                ", stationId1=" + stationId1 +
                ", stationId2=" + stationId2 +
                ", wifiStrength1=" + wifiStrength1 +
                ", wifiStrength2=" + wifiStrength2 +
                ", createtime=" + createtime +
                ", tempPositionName='" + tempPositionName + '\'' +
                '}';
    }
}
