package com.cst.xinhe.persistence.model.overman_area;

import java.util.Date;

public class OvermanArea {

    private Integer overmanAreaId;
    private Integer warningAreaId;
    private Integer maxOverman;
    private Date startOvertime;
    private Date endOvertime;
    private Integer staffId;
    private String remark1;
    private String remark2;

    private Integer remark3;

    private String warningAreaName;
    private  Integer containNumber;

    public String getWarningAreaName() {
        return warningAreaName;
    }

    public void setWarningAreaName(String warningAreaName) {
        this.warningAreaName = warningAreaName;
    }

    public Integer getContainNumber() {
        return containNumber;
    }

    public void setContainNumber(Integer containNumber) {
        this.containNumber = containNumber;
    }

    public Integer getOvermanAreaId() {
        return overmanAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overman_area.overman_area_id
     *
     * @param overmanAreaId the value for overman_area.overman_area_id
     *
     * @mbg.generated
     */
    public void setOvermanAreaId(Integer overmanAreaId) {
        this.overmanAreaId = overmanAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overman_area.warning_area_id
     *
     * @return the value of overman_area.warning_area_id
     *
     * @mbg.generated
     */
    public Integer getWarningAreaId() {
        return warningAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overman_area.warning_area_id
     *
     * @param warningAreaId the value for overman_area.warning_area_id
     *
     * @mbg.generated
     */
    public void setWarningAreaId(Integer warningAreaId) {
        this.warningAreaId = warningAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overman_area.max_overman
     *
     * @return the value of overman_area.max_overman
     *
     * @mbg.generated
     */
    public Integer getMaxOverman() {
        return maxOverman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overman_area.max_overman
     *
     * @param maxOverman the value for overman_area.max_overman
     *
     * @mbg.generated
     */
    public void setMaxOverman(Integer maxOverman) {
        this.maxOverman = maxOverman;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overman_area.start_overtime
     *
     * @return the value of overman_area.start_overtime
     *
     * @mbg.generated
     */
    public Date getStartOvertime() {
        return startOvertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overman_area.start_overtime
     *
     * @param startOvertime the value for overman_area.start_overtime
     *
     * @mbg.generated
     */
    public void setStartOvertime(Date startOvertime) {
        this.startOvertime = startOvertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overman_area.end_overtime
     *
     * @return the value of overman_area.end_overtime
     *
     * @mbg.generated
     */
    public Date getEndOvertime() {
        return endOvertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overman_area.end_overtime
     *
     * @param endOvertime the value for overman_area.end_overtime
     *
     * @mbg.generated
     */
    public void setEndOvertime(Date endOvertime) {
        this.endOvertime = endOvertime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overman_area.staff_id
     *
     * @return the value of overman_area.staff_id
     *
     * @mbg.generated
     */
    public Integer getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overman_area.staff_id
     *
     * @param staffId the value for overman_area.staff_id
     *
     * @mbg.generated
     */
    public void setStaffId(Integer staffId) {
        this.staffId = staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overman_area.remark1
     *
     * @return the value of overman_area.remark1
     *
     * @mbg.generated
     */
    public String getRemark1() {
        return remark1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overman_area.remark1
     *
     * @param remark1 the value for overman_area.remark1
     *
     * @mbg.generated
     */
    public void setRemark1(String remark1) {
        this.remark1 = remark1 == null ? null : remark1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overman_area.remark2
     *
     * @return the value of overman_area.remark2
     *
     * @mbg.generated
     */
    public String getRemark2() {
        return remark2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overman_area.remark2
     *
     * @param remark2 the value for overman_area.remark2
     *
     * @mbg.generated
     */
    public void setRemark2(String remark2) {
        this.remark2 = remark2 == null ? null : remark2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column overman_area.remark3
     *
     * @return the value of overman_area.remark3
     *
     * @mbg.generated
     */
    public Integer getRemark3() {
        return remark3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column overman_area.remark3
     *
     * @param remark3 the value for overman_area.remark3
     *
     * @mbg.generated
     */
    public void setRemark3(Integer remark3) {
        this.remark3 = remark3;
    }
}